### ISSUE TITLE
Button, Select, Input html Tags Displaying Tiny with no Text

### ISSUE THREAD

**Issue by fictitiousexistence** [luakit/luakit#1024]
luakit 2.3.3
  built with webkit 2.38.2 (installed version: 2.38.2)

Certain html tags do not dispaly properly, ex: input, select, button. 

This link is an example of a select and a input tag:
[https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select](url)

This is how is should look (example in firefox):
![firefox](https://user-images.githubusercontent.com/20089581/204941403-48a5bdf0-7bba-4e3e-8be8-caf78483983c.png)

This is how it looks in luakit:
![webkit](https://user-images.githubusercontent.com/20089581/204941413-6e82b189-35b7-405e-b8e4-51d3c99ba923.png)

This happens for me on both Gentoo and Arch and with any webkit browser like nyxt. 
I was not sure if I should post here or not but the luakit specific pages like the one for tls warnings show the same issue:
![tls_warning](https://user-images.githubusercontent.com/20089581/204941737-87d8b1ca-0b35-4b4b-b0dd-e27eb7b5020b.png)

All the font specific attributes show as -webkit-small-control;
![screenshot_2022-11-30-201301](https://user-images.githubusercontent.com/20089581/204942078-721e9e53-72b3-44f1-a618-ba463ab02e47.png)

I put the following as a custom style and it solves the issue for all pages except ones like the tls warning page. 
`@-moz-document regexp('.*') {`
`	body, div, button, form, input, textarea, select, isindex, datagrid {`
`    font: inherit;`
`}`
`}`

I have the following font settings set:

`["webview.default_font_size"]=10,`
`["webview.default_monospace_font_size"]=10,`
`["webview.minimum_font_size"]=0,`

Changing minimum font size did not change anything.

Is this a bug or am I just doing something wrong? 
Or does it just need fixed on webkits end?

Thanks!

**Comment by henkmet** [comment]
I copy-pasted your link and it shows perfectly fine for me.
luakit 2.3.1-6-ge9c7693f
  built with webkit 2.38.2 (installed version: 2.38.2)
![display](https://user-images.githubusercontent.com/3350726/204948796-f48aa5af-b8cd-402d-827b-7121b790c2f0.png)
(I think archlinux/aur system doesn't update the name nicely. It's the up-to-date git version)
ETA: This is on X11 if that matters.

**Comment by taobert** [comment]
That it's happening with multiple webkit browsers suggests that webkit is involved,
but that it's happening on multiple systems you've installed, and not to other people, kinda hints that you're involved too. Luakit's chrome pages are just html that gets rendered by webkit like everything else, so those not working is not profound.

Maybe webkit's trying to use a font that isn't installed?
This is not obviously the problem, since in my hands, both the main text and the input/selects are rendered in `Bitstream Vera Sans` (similar to @henkmet's picture), but i notice that in the picture you give for firefox' rendering, the main text is seriphed but not the select/input, so there is at least precident for _some_ browsers to use different families for different elements.
Can you confirm that this font is used for the text that you _can_ see?

You could also try overriding the font with one that you know is installed eg: `style="font-family: Times; font-size: 24pt;"`

(I'm also running under X11.)

**Comment by fictitiousexistence** [comment]
Got it working now. Completely my bad.

The font I was using was working everywhere else so I didn't even realize that inside of dconf-editor you are supposed to specify the font size. 

I specified only the font, which worked for everything else, but for webkitgtk apps I needed to specify the default size too. 
![screenshot_2022-12-01-072733](https://user-images.githubusercontent.com/20089581/205052918-8b4fbdf9-ee8e-4be2-a758-a79755aafbb7.png)
