### ISSUE TITLE
Migrate to webkit2gtk-4.1, javascriptcore-4.1 and libsoup-3.0

### ISSUE THREAD

**Issue by fictitiousexistence** [luakit/luakit#1025]
Updated gentoo system today including webkit-gtk to 2.38.2-r500

Tried to rebuild luakit master and got the following message:

`Package webkit2gtk-4.0 was not found in the pkg-config search path.`
`Perhaps you should add the directory containing webkit2gtk-4.0.pc'`
`to the PKG_CONFIG_PATH environment variable`
`Package 'webkit2gtk-4.0', required by 'virtual:world', not found`
`Package 'javascriptcoregtk-4.0', required by 'virtual:world', not found`
`config.mk:109: *** Cannot find required package(s\) to build luakit. Please check` `you have the above packages installed and try again.  Stop.`

Then I found this [https://discourse.gnome.org/t/webkit2gtk-4-1-added-to-gnome-sdk-webkit2gtk-4-0-deprecated/7053](https://discourse.gnome.org/t/webkit2gtk-4-1-added-to-gnome-sdk-webkit2gtk-4-0-deprecated/7053)

Thanks

**Comment by c0dev0id** [comment]
Hi,

Most distributions are allowing to install both at the same time.

I briefly tried to switch luakit to 4.1 by changing webkit2gtk-4.0 and javascriptcoregtk-4.0 to 4.1 in `config.mk`. It will then also pull in libsoup-3.0, which is incompatible.

I've created branch [webkit2gtk-4.1](https://github.com/luakit/luakit/tree/webkit2gtk-4.1) to work on. I'm not sure yet how much effort this is. A minimum would be to work through the libsoup migration document here: https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html

**Comment by taobert** [comment]
I've [cloned](https://github.com/taobert/luakit/tree/webkit2gtk-4.1) that branch, and updated the soup bits so that it compiles and runs well enough to type this in.
The code's too messy to PR it to `develop`, and i don't trust that the changes haven't screwed up memory management, 
but it might be useful as a reference.

**Comment by fictitiousexistence** [comment]
Thanks @taobert 
I just ran it for the last hour for my normal morning routines and did not run into any issues. 
I usually open up 20+ tabs.

**Comment by c0dev0id** [comment]
Cool! I was also working on it, but mine is not compiling yet. I'm pulling your change in and we continue from there. You can always send PRs towards this branch. I'll merge them when they work for me.

We can do a proper code review when I create a PR from the webkit2gtk-4.1 to the develop branch.

**Comment by c0dev0id** [comment]
Well, yeah - that diff looks a bit freaky. But it helped me to understand a thing or two. I'm also not sure if `g_free()` or `g_uri_unref()` should be used on GUri. Maybe both is possible...  But as we never call `g_uri_ref()`. I assume calling `g_free()` on it is fine.

As for the GET_PROP juggling... I hope there's a better solution.

**Comment by taobert** [comment]
Yah.
I regarded it as an exploratory exercise rather than a finished product.

If there's a `g_uri_unref()` then that's almost certainly what is wanted.
These patches are the only things that come up when i grep for "GUri",
so not finding `g_uri_unref()` elsewhere in the code is not profound.

Perhaps there's a way for the `GET_PROP` shit to be less offensive, but that was what seemed to be available.
Since `GUri` is immutable, it needs to be recreated any time it's changed.
An alternative would be to collect all the strings and pass them once to `g_uri_join()`.
This would be sevenish fewer calls to a `g_uri_.*()`, 
but would still entail creating and freeing a `gchar *` for each entry
(albeit at the top and bottom of the function rather than in the macro).

A second alternative, then arises that  if we already have those strings at that point,
we might as well just make the string. In an earlier iteration i had:
```c
...
    if(scheme){
        g_string_append(uri_string, scheme); 
        g_string_append(uri_string, "://"); 
    }
    if(host){          // I'm assuming, (possibly incorrectly) that a password /must/ have a user,
        if(user){      // and a users and ports /must/ have a host.
            g_string_append(uri_string, user); 
            if(password){
                g_string_append(uri_string, ":"); 
                g_string_append(uri_string, password); 
            }
            g_string_append(uri_string, "@"); 
        }
        g_string_append(uri_string, host); 
        if(port) { 
            g_string_append(uri_string, ":"); 
            g_string_append(uri_string, port); 
        }
    }
    if(path){
        g_string_append(uri_string, "/"); 
        g_string_append(uri_string, path); 
    }
    if(fragment){
        g_string_append(uri_string, "#"); 
        g_string_append(uri_string, fragment); 
    }
    if(query){
        g_string_append(uri_string, "?"); 
        g_string_append(uri_string, query); 
    }

    lua_pushstring(L, uri_string->str);
...
```
A third alternative, is that `luaH_soup_uri_tostring()` is only called twice from `lib/go_up.lua` and once from `lib/lousy/uri.lua`, 
so skipping glib entirely and just moving the string building logic to `lib/lousy/uri.lua` might be acceptable.
Being able to use lua's string concatenation operator would make the string building quite a lot shorter.

**Comment by taobert** [comment]
It seems that the old and new functions don't operate quite the same in at least one case.
If there's no port (eg when a `file:///` url is parsed) `soup_uri_new()` reports this as 0,
whereas `g_uri_get_port()` returns -1.

This is propagated into lua by `soup_push_uri()`:
```c
    if (uri->port) {
        lua_pushliteral(L, "port");
        lua_pushnumber(L, uri->port);
        lua_rawset(L, -3);
    }
```

and causes (at least) a failure in the `passmanager` plugin where it's assumed that if the port equates to true,
that there's necessarily a host:
```lua
    local domain = _uri.host
    if _uri.port and _uri.port ~= 80 and _uri.port ~= 443 then
        domain = domain .. ":" .. _uri.port
    end
```
It's fairly trivial to change `soup_push_uri` to omit the port,
but i don't know whether the `g_uri_...` suite will break if they don't later get a `-1` when they're expecting it.



Edit: Corrected `g_uri_get_host()` to `g_uri_get_port()`.

**Comment by fictitiousexistence** [comment]
@taobert I hate to admit this. But my pickle was a bit lousy this morning. 

I was running your [clone](https://github.com/taobert/luakit/tree/webkit2gtk-4.1) for webkit2gtk-4.1 for a bit. I pulled it again and rebuilt it and now am getting some silly message about /lousy/pickle when opening the "command prompt" (not sure what its called.)

Think this is related to your clone or a new issue?
Thanks!

![screenshot_2023-01-05-191454](https://user-images.githubusercontent.com/20089581/210904142-17dbdfe0-23c4-442f-ac41-32f320ee43b8.png)

**Comment by taobert** [comment]
Umm.. 
Well i haven't changed that tree recently, and it's not failing for me.
But i _am_ sorry to hear you're having trouble with your gentables.

I can make that error happen if i deliberately mung my `command_history` file, 
so check to make sure that that's well formed (or just delete it).

**Comment by fictitiousexistence** [comment]
You fixed my pickle. Thanks!

**Comment by taobert** [comment]
I added PR #1034, it didn't automatically tag this issue.

**Comment by c0dev0id** [comment]
Hmm. I merged your PR, but I don't have much luck running it.
```
$ ./luakit
Abort trap
```
But I doubt it's the the PR because I reverted to the previous version and see the same. 

I'm just saying that this went in pretty much untested. Feedback on this branch is welcome.

**Comment by fictitiousexistence** [comment]
@taobert  This is what I got after compiling:

└─[$] luakit --check                                                                                                                      
[    0.000499] I [core/luah]: Loading rc: ./config/rc.lua
Configuration file syntax OK.

└─[$] luakit --version
luakit 2.3.3-10-gc5ef753a
  built with: webkit 2.38.3 (installed version: 2.38.3)
                 GTK 3.24.35 
                GLIB 2.74.4 
                SOUP 3.2.2

**Comment by taobert** [comment]
Yeah, i see what @fictitiousexistence sees.
I just checked out a clean clone, and moved my `~/.config/luakit` to confirm.

It seems to be bailing fairly early.
I'd have expected that there'd be some output printed before any of the uri-processing stuff got executed, so that's interesting.
The extra version info in `luakit.c` would probably be early enough,
but it's pretty much cut and pasted from the version info that was there already.
Upgrading from `G_APPLICATION_FLAGS_NONE` to  `G_APPLICATION_FLAGS_DEFAULT` would probably also be early enough,
but unless i misread, that's the recommended change. 
Maybe one of the headers i deleted from `widgets/webview/auth.c` is needed on BSD, but that's a real long shot.

Is it possible that a library's not getting found?
Can you get a backtrace from gdb?

**Comment by taobert** [comment]
I see you're runing `./luakit` with a leading `./`, and so (i guess) using the `DEVELOPMENT_PATHS` infrastructure.
I've been `make install`-ing every build, and don't have much experience with this.
Is it possible your paths are whacky, and you're somehow pairing `./luakit` with `/usr/local/lib/luakit/luakit.so`?
I just had a play to see if i could make that happen, but couldn't.

**Comment by c0dev0id** [comment]
Good thought, but that was not it. My home directory doesn't allow applications to set memory writable and executable at the same time. This setting has bitten me before. I just forgot about it, because it doesn't happen once the software is installed and in /usr/local, which allows this operation. Anyway, that's OpenBSD specific.

It works for me now. I'll create a PR for develop to review.

**Comment by oz123** [comment]
@c0dev0id can you please tag a new release which includes this fix?

**Comment by mattst88** [comment]
> @c0dev0id can you please tag a new release which includes this fix?

Any chance we could get a tagged release with webkitgtk-4.1 support?
