### ISSUE TITLE
The website's not up to date

### ISSUE THREAD

**Issue by matteopt** [luakit/luakit#1031]
As discussed in https://github.com/luakit/luakit.github.io/pull/5, the [luakit website](luakit.github.io) does not offer complete information about what packages are available for installation.  
As an example, on Arch Linux another package is present besides the `luakit-git` AUR package, the `luakit` community package. The diference between them is the AUR package always pulls from this repository's `develop` branch and builds from source, it is not a binary package.  
  
I'm posting this here for posterity as nobody can currently merge things in the other repository.

**Comment by taobert** [comment]
Since the incompleteness can't really be resolved here,
maybe change the title to something catchy like "Arch has a binary package available in community".
Alternatively, it might be worthwhile to have a single sprawling thread for all of the website's inacuracies,
in which case "The website's not up to date" might be better.

**Comment by c0dev0id** [comment]
No, please create pull requests against the luakit.github.io repository. I got access to the website repo recently and can merge them.
