### ISSUE TITLE
add metager engine 

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#1053]
**Current Behavior:**I follow setting on Arch Linux Wiki:
~/.config/luakit/userconf.lua

local engines = settings.window.search_engines
engines.meta          = "default https://metager.org/search?q=%s"

I like to use metager search engine but luakit with my settings doesn't start.

Luakit doesn't start.
**Desired Behavior:**
II like to use as default search engine

**How can we reproduce it (step by step):**

**Environment:**

FreeBSD 13.2-RELEASE
Output of `luakit --version`: luakit 
 built with webkit 2.34.6 (installed version: 2.34.6)

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org

**Comment by taobert** [comment]
> local engines = settings.window.search_engines
engines.meta = "default https://metager.org/search?q=%s"

Where did you find this syntax?
Each `search_engine.name` should be a string into which the search term can be substituted to produce a URL to query a web search engine. (Edit: for completeness, it can also be a function which returns a string.)
So, there are two things here:
URIs don't tend to start with "default ", so that should probably not be there.
And seemingly, the URI part of your string isn't the URI format that metager uses.

Regarding the first, if you want to set metager to be the default search engine (so you can do `:open my search terms` rather than `:open meta my search terms`), then you may need to (also?) use:
```lua
engines.default = "<whatever the correct url is>"
```
Regarding the second, do a metager search, and use the resultant address to determine a minimum substitutable URI that will work for your purposes.


> I like to use metager search engine but luakit with my settings doesn't start.

Well, a failure to start is difficult to diagnose if you don't provide the console output.
Is the quoted snippet the extent of your `userconf.lua`?
If so, you may need to add:
```lua
local settings = require "settings"
```
at the top.

**Comment by c0dev0id** [comment]
I've set duckduckgo as my default search engine like this:
```lua
local settings = require "settings"
settings.window.search_engines.ddg = "https://duckduckgo.com/?q=%s"
settings.window.search_engines.g = "https://google.com/?q=%s"
settings.window.search_engines.mg = "https://metager.org/?q=%s"
settings.window.search_engines.gh = "https://github.com/search?q=%s"
settings.window.search_engines.default = settings.window.search_engines.ddg
```

As you can see, multiple search engines can be defined. You can  select them right at the open prompt. `:open mg test` would search "test" on metagear. `:open g foo` would search foo on google. That's why I give them short keys.

**Comment by ghost** [comment]
Thank you very much for the help. 
The link which I mention where I found my settings is:
[https://wiki.archlinux.org/title/Luakit](https://github.com/luakit/luakit/issues/url)

**Comment by c0dev0id** [comment]
The archwiki entry is correct.

Once you have his line,
```lua
local settings = require "settings"
```
you can create a new variable `engines` as a short form with this:
```lua
local engines = settings.window.search_engines
``` 
then you can use `engines` instead of typing the long `settings.window.search_engines` path.
```lua
engines.mg = "https://metager.org/?q=%s"
engines.default  = engines.mg
```

The part that was not correct in your initial post was this one:
```
engines.meta = "default https://metager.org/search?q=%s"
```
"default " does not belong into the search engine string. I don't see this syntax in the archwiki post.
