### ISSUE TITLE
[Question] How to reload programatically?

### ISSUE THREAD

**Issue by wsw70** [luakit/luakit#1054]
I use Luakit to display a non-interactive home dashboard full-screen. The dashboard's content is updated via a CI/CD pipe. It would be wonderful if I could reload Luakit programmatically (via a signal for instance) so that I do not have to reboot the whole system (which is what I do today).

Is this possible with Luakit?

**Comment by taobert** [comment]
You may need to help me out a bit here.
From the little bit of reading i just did, CI/CD pipelines are a software development workflow technique,
and not something that i'd expect to be updating dashboard content.
There's not currently an elegant way to trigger luakit behaviour from outside luakit,
but if you can build a command line and exec it, you have a couple of options. 

I have in the past added a scheme to allow me to restart luakit from a cron job. 
This is insecure, and allows any website to also restart luakit.
However, if you _know_ that your instance will only look at trusted sites, it may be workable for you.

```lua
local webview = require "webview"
webview.add_signal("init", function (view)
    view:add_signal("scheme-request::command", function (v, uri, request)
        if uri == "command://restart" then
            w = webview.window(v);
            w:close_tab();
            w:restart();
        end 
    end)
end)
```

With this in place, calling `luakit command://restart` triggers the restart.

#572 discusses the possibility of an external client to interface with luakit,
and includes a more invasive, but maybe more secure, version of the code above.
#295 is resolved by using `xdotool` to interface to luakit, so that may also be an option.

**Comment by wsw70** [comment]
> You may need to help me out a bit here.
> From the little bit of reading i just did, CI/CD pipelines are a software development workflow technique,
> and not something that i'd expect to be updating dashboard content.

I use Luakit to display a home dashboard (an SPA based on Vue that gathers weather forecast, Google Calendars for the family etc. and present all this in a summarized, easy to parse format). It is displayed on a screen mounted to the wall that does not have any HID (keyboard, mouse). So the only way to interact with it is either programmatically, or by physically switching off an on the server (which is a Raspberry Pi).

In order to update the SPA, I have my code on a git server and everytime I push code, the SPA is rebuilt and the resulting HTML, CSS, JS, ... is copied to that RPi server. It is not enough for the page to be updated visually, though - Luakit needs to reload the page.

My solution so far was to either force a reload by the JS code or programmatically reboot the server (or even electrically reboot the server - it is connected to a smart plug). All of this works with more or less gymnastics but the most natural way would be to request Luakit to reload/restart.

I will try your solution today - thank you very much for the answer!

**Comment by taobert** [comment]
Neat.:)
It would be somewhat more efficient to use `v:reload()` than to `w:restart()` luakit,
but you'd need to do some extra juggling to determine the correct `v` to call it with
(because the `unique` infrastructure will open the command:// uri in a new tab/webview).

For completeness, since it seems that you would only have one tab and so session-saving is probably unimportant,
some variant of `killall -KILL luakit ; luakit&` might be the quickest to implement.

**Comment by wsw70** [comment]
> For completeness, since it seems that you would only have one tab and so session-saving is probably unimportant,
> some variant of `killall -KILL luakit ; luakit&` might be the quickest to implement

... and this is what I ended up doing - the simplest solutions are often the best ones! Thank you very much for your help!

**Comment by c0dev0id** [comment]
Just in case you didn't know. The suckless "surf" browser has a kiosk mode and it reloads the page when you send it a SIGHUP signal.

This may be a better fit for the task.
