### ISSUE TITLE
Fullscreen hides both the statusbar and the tabbar

### ISSUE THREAD

**Issue by duarm** [luakit/luakit#1066]
**Current Behavior:**

Going fullscreen hides both the statusbar and the tabbar

**Desired Behavior:**

An option to override this behaviour, I don't want a fullscreen window to hide both bars

**How can we reproduce it (step by step):**

Press F11 or your window manager specific shortcut

**Environment:**

Linux Distribution & Version:
luakit 2.3.3-15-gb143b383
  built with: webkit 2.42.3 (installed version: 2.42.3)
                 GTK 3.24.38
                GLIB 2.78.3
                SOUP 3.4.4

**Comment by taobert** [comment]
The tab and status bar are hidden in the signal handler for `property::fullscreen`.
You can remove all handlers for this signal by adding:
```lua
window.add_signal("init", function (w)
    w.win:remove_signals("property::fullscreen")
end)
```
to your `userconf.lua` file.
If you want to finesse things further, you could then write your own handler to do that (see `lib/window.lua` for examples).
I don't remember why i don't do it this way. Perhaps it had other unintended consequences.

Alternatively, (what i do) since the default handler calls `window.update_sbar_visibility`,
if what you're after is to leave the status bar in place, you could override `update_sbar_visibility` to make sure it stays visible:
```lua
window.add_signal("init", function (w)
    w.update_sbar_visibility_old = w.update_sbar_visibility
    w.update_sbar_visibility = function (w)
	w:update_sbar_visibility_old()
	w.bar_layout.visible = true
    end,
end)
```

**Comment by duarm** [comment]
Thanks, the first solution worked perfectly. The second solution only hides the statusbar, and I can't simply `w.tablist.visible = true` inside `update_sbar_visibility` because `hide_ui_on_fullscreen` calls `w.tablist.visible = not win.fullscreen` right after
