### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#1070]
From all the activity I'm seeing (none) and the open issues (218), it seems like the project is dying. 
Please don't end up like uzbl, I love this browser and the simplicity of it. Don't abandon it.

**Comment by taobert** [comment]
So, submit some PRs.
Luakit has a very small developer base who contribute in their spare time, working around other commitments.
Of the 218 open issues, some are completed but not closed and some are so old they may no longer be relevant.
Many are genuinely open problems of varying (though generally low) severity.
Chose one that you feel looks interesting and work on it.

**Comment by ghost** [comment]
I would love to submit some pull requests, sadly I don't know any C and I am not good enough with Lua (still learning) to contribute yet.

**Comment by c0dev0id** [comment]
While I have commit access to the repo, I'm not the owner of the project. Therefore I'm not telling people "no" in issues and PRs and let them hang around. I'm not sure if @aidanholm is still interested in luakit.

I'd be happy to talk about the future of luakit with some of the more active people here. Feel free to join the \#luakit IRC channel on OFTC (my nick is sdk_ there).

**Comment by c0dev0id** [comment]
To put an end to the inactivity, I created release 2.3.4, which basically only contains the libsoup3 and webkit 4.1 support. That one was long overdue.

Furthermore I merged some of the PRs. Those are not yet well tested, which is why I merged them after the release. Let's see how it goes.

EDIT: okay, even though the webkit41/libsoup3 has been in luakit HEAD for a year, this should not have been a release. I also think it was wrong to not give it a minor bump at least. I'm trying to fix the bugs (see last two issues I opened) and create another release with the right number bumped... :/

**Comment by aidanholm** [comment]
@c0dev0id, you have been the de facto owner for a while now :)  I have just sent an invite to make it official

I am still interested, but unfortunately have very little time to contribute -- please feel free to set the project direction as you see best, and thank you for your many contributions here!

**Comment by c0dev0id** [comment]
@aidanholm Oh, thank you. I accepted the invite. And thanks for setting the CI workflow up again. That helps. And thanks for trusting me with the project :heart:

**Comment by c0dev0id** [comment]
I think the question has been answered.
