### ISSUE TITLE
Zoom level and scrolling inconsistency

### ISSUE THREAD

**Issue by mucksailor** [luakit/luakit#1086]
**Current Behavior:**

Zoom level is randomly sometimes much higher than it should be, and sometimes/on certain sites this prevents scrolling.
Per this [issue](https://github.com/luakit/luakit/issues/1013), I tried to comment out the styles import in rc.lua, which seemed to change nothing.
I am using high DPI on X11 (159), but the zoom level setting for luakit is the default.
Attempted to reproduce behavior in another webkit browser (Midori), to no avail. The behavior appears to be unique to luakit.

**Desired Behavior:**

Consistency of zoom level and ability to scroll.

**How can we reproduce it (step by step):**

Run luakit a few several times after installing it with xbps or building from source.

**Environment:**

Linux Distribution & Version: Void Linux x86_64 glibc
Output of `luakit --version`:
```
luakit 2.3.6
built with: webkit 2.42.5 (installed version: 2.44.2)
GTK 3.24.42
GLIB 2.80.0
SOUP 3.4.2
```
Also tried compiling from source:
```
luakit 2.3.6-17-gfc115f50
built with: webkit 2.44.2 (installed version 2.44.2)
GTK 3.24.42
GLIB 2.80.3
SOUP 3.4.2
```

**Comment by imiric** [comment]
I'm having a similar issue, except that the zoom levels are much lower than configured.

I have `settings.webview.zoom_level = 150` in my `userconf.lua` and this has worked fine up until a few weeks ago. Suddenly the default zoom level on sites I haven't visited is 100%, and I have to manually zoom in. The levels also don't seem to be remembered and get reset at some point, but I haven't noticed a pattern.

I've also tried disabling the styles module and deleting `styles.db`, but that didn't have an effect.

My version:
```
luakit 2.3.6
  built with: webkit 2.42.5 (installed version: 2.42.5)
                 GTK 3.24.42
                GLIB 2.80.0
                SOUP 3.4.2
```

This is on Void Linux. Note that I'm holding back the webkit2gtk package because of #1081.

As for the scrolling issue, this has been a constant issue with Luakit on some sites, which are usually JS heavy, or mess with browser scrolling in some way. I have to open these in another browser. It's annoying, but I've learned to live with this issue for years now. I don't think it's related to the zoom feature.
