### ISSUE TITLE
Auto-complete for input elements

### ISSUE THREAD

**Issue by daGrevis** [luakit/luakit#164]
Is it possible to have auto-complete for field elements? Maybe there is plugin?

**Comment by c0dev0id** [comment]
Yes, the formfiller can do exactly this.

Example `.local/share/luakit/forms.lua`:
```
on 'https://github%.com/login' {
  form {
    method = 'post',
    action = '/session',
    input {
      id = 'login_field', name = 'login', type = 'text',
      value = 'c0dev0id',
    },
    input {
      id = 'password', name = 'password', type = 'password',
      value = pass("Internet/Github"),
    },
    submit = true,
    autofill = true,
  },
}
```

Read the formfiller documentation in `:help`, there are shortcuts to create these entries automatically. You can also set `submit` to "false", so values are entered and you can change them before submitting.

This issue is 6 years old. I'm closing it. Feel free to reopen / create a new one.
