### ISSUE TITLE
How to get luakit automatic in kiosk mode (like you press f11)

### ISSUE THREAD

**Issue by Hebuss** [luakit/luakit#225]
Hi i can't find a way to start up luakit in kiosk mode, (like you press f11 but then automatic).
I searched the web and found nothing? 
I'm running this on a raspberry pi using lxde.

Is this not possible ?

gr. Hebuss

**Comment by pepa65** [comment]
I get `no windows spawned by rc file, exiting`...

**Comment by lblabr** [comment]
i'm new to luakit, im interested to get luakit in fullscreen mode, where do i get the relevevant file?

**Comment by taobert** [comment]
Erm.
If you mean "where do you get a copy of `rc.lua` that @Plaque-fcc suggests that you edit?"
then you can copy that from `/etc/xdg/luakit/rc.lua`.

**Comment by taobert** [comment]
...however, the opinion has been expressed that users editing `rc.lua` should be deprecated in favour of `userconf.lua`.
If you wanted to do this using just `userconf.lua`,
you could either add an `init` signal so that `window` fullscreens itself automatically (Edit: props to @gearhead in #974):
```lua
local window = require "window"
window.add_signal("init", function (w)
     w.win.fullscreen = true; 
end)
```
or override `window.new` to do some extra work (as @nathanharper suggests):
```lua
local window = require "window"
window.old_new = window.new
window.new = function(args)
    w = window.old_new(args);
    w.win.fullscreen = true;
    return w;
end
```
