### ISSUE TITLE
doc.luakit.org/html/ is gone

### ISSUE THREAD

**Issue by JonasT** [luakit/luakit#276]
doc.luakit.org/html/ is gone, and the README doesn't link a full API reference. This should be considered a basic requirement for anything with a non-trivial api like luakit. It would be pretty good if you could fix that again.

**Comment by Plaque-fcc** [comment]
Isn't that a duplicate of #271?

**Comment by JonasT** [comment]
That discussion seemed to focus on the wiki/non-reference parts. While the wiki replaces that nicely as answered in #271, it doesn't seem to contain the API reference anymore.

**Comment by o-jasper** [comment]
Could `luakit://help/` have some sub pages with the reference locally? Or link to the local file. Also might be nice to have an aid showing you  a `add_binds({key(..)})` or `add_binds({but(...)})` that is triggered by keys held down.

**Comment by Plaque-fcc** [comment]
I thought it even calls a VIm in a terminal window when you click on
that file.
Or I'm having a delirium?

**Comment by mason-larobina** [comment]
Sorry about this. When I moved luakit.org to github pages a few things were lost.

The same docs are available by running `make doc` as mentioned in #271. Unless you meant something else? 

@o-jasper: Perhaps, but only if they were generated and installed somewhere. Otherwise it wouldn't be able to generate the doxygen output at runtime.
