### ISSUE TITLE
Hangs on bitbucket.org

### ISSUE THREAD

**Issue by Yavor-Ivanov** [luakit/luakit#288]
Whenever I visit [bitbucket](bitbucket.org) with scripts enabled, the site loads to about 80 percent and then luakit freezes. I've ran luakit from the terminal, but get no output when this happens. The window is completely unresponsive and won't redraw.

**Comment by JLoureir0** [comment]
Same problem here, site loads up to 89% and then freezes

**Comment by ron-wolf** [comment]
This link should work: http://bitbucket.org. In Markdown, `(bitbucket)[bitbucket.org]` links to `$CURDIR/../bitbucket.org` — in this case, https://github.com/mason-larobina/luakit/issues/bitbucket.org. You have to add `http(s)://` to make it an absolute link rather than a relative link within the current site.

**Comment by aidanholm** [comment]
Closing; since this is site-specific and luakit has recently been updated to use WebKit 2.
