### ISSUE TITLE
current development

### ISSUE THREAD

**Issue by myf** [luakit/luakit#299]
it seems that luakit has been hibernate for quite a bit. Other similar projects such as qutebrowser etc. has migrated to webkitgitk2 and we are still on 1.0, which is slated for decommission. However it seems that this for at https://github.com/aidanholm/luakit is pretty active recently and it will be good to make a more-up-to-date version of luakit again. However since it's a fork there 's no separate issues page. I wonder if the folks here have anyway to contact / work with the fork owner (@aidanholm) there.

**Comment by aidanholm** [comment]
I'm happy to accept patches, PRs, etc. I'm mostly working on getting a mostly-unbroken Webkit 2 port going, and there's no shortage of issues yet.

I'm unsure if my approach would mesh well with what other people have been doing, since the shift to Webkit 2 requires some radical changes; I've added a second Lua state that runs on the web process, a Lua interface for loading modules onto that state, Lua signal based IPC, a partial Lua DOM API (ugh) so that the follow mode can operate in all frames (non-main-frame JS contexts are inaccessible in Webkit 2)... it's all very ad-hoc at the moment.

**Comment by XVilka** [comment]
@aidanholm probably you want to join this organization https://github.com/luakit-crowd
Just ask @Plaque-fcc or @liuch .
It would be cool if your fork would become mainstream.

**Comment by aidanholm** [comment]
@XVilka Sure; I noticed luakit-crowd before forking, but it seems fairly inactive?

**Comment by XVilka** [comment]
@aidanholm it's inactive because this team missing you ;)
And it would be great if the main site http://luakit.org would point to your fork then. Probably @mason-larobina would want to do this redirect then.

**Comment by aidanholm** [comment]
Well, if @Plaque-fcc / @liuch feel that my approach to a Webkit 2 port is worth pursuing I'd be happy to contribute / work collaboratively. I'm definitely going to keep working on luakit either way, because I want a better browser for myself :)

**Comment by ff2000** [comment]
It would be great to see some action on luakit! Gentoo is about to remove it because of inactivity and the insecure webkit-gtk it depends on.
I currently play with @aidanholm 's fork and would have some minor issues to report, but currently there is no bugtracker neither for luakit-crowd nor for aidanholm's fork. IMHO there is a button somewhere to enable an issue tracker (at least I already saw a fork activating issues). The current situation is discouraging for users, as they only see the issue tracker for the main repo that is definitely inactive.
As it looks there are still luakit-users around and DEVs interested in coding for it. Hopefully this won't fall asleep, again :)

**Comment by mason-larobina** [comment]
Archlinux is using the luakit-crowd repo for the official luakit package.

That seems reasonable to me. I wish that the luakit org name on github was available, I'd move my repo there and give access to the luakit crowd folks.

**Comment by mason-larobina** [comment]
Good news everyone!

I've contacted Github support and created a github org for the continuing maintainership/development of luakit: https://github.com/luakit

And moved my luakit repo there: https://github.com/luakit/luakit

It's hard to tell who the existing members of luakit-crowd are but I'd like to give them access to the luakit org.

**Comment by myf** [comment]
Great news!

**Comment by aidanholm** [comment]
@ff2000 I've enabled issues, so feel free to report any (and thanks!)

**Comment by mason-larobina** [comment]
I've also update luakit.org to redirect to https://luakit.github.io/luakit/ and all the offlinks on that page to point to luakit/luakit.

**Comment by aidanholm** [comment]
@mason-larobina The old page at https://mason-larobina.github.io/luakit/ now 404s; should probably be redirected as well.

**Comment by mason-larobina** [comment]
Hmm, I was led to believe github would redirect that automatically. They said if I created another repo with the same name it would cancel the redirect.

**Comment by mason-larobina** [comment]
I've contacted github support about the missing redirects.

**Comment by aidanholm** [comment]
I've merged my work on luakit into this repository after @mason-larobina contacted me (aidanholm/luakit#388). I think I merged most, if not all, of the luakit-crowd changes at some point.

Going forward, I intend to continue working on luakit as my time permits, and slowly cut through the backlog of open issues/PRs here. I'll continue to push changes to both repositories for the time being, and I plan on a stable release fairly soon.

Hopefully that answers most of the questions about current development! I'll close this issue now; feel free to reopen it if you have further questions.
