### ISSUE TITLE
Merge issues from aidanholm/luakit?

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#315]
Do we?

**Comment by groolot** [comment]
Do you also want some help to clean up this project's issues? Removing, labelling, milestoning, etc.?

**Comment by aidanholm** [comment]
Let's keep them separate for now. This repository has many issues that are no longer valid; it'd be good to get rid of those before thinking about merging.

The other obvious problem is the ambiguity of issue numbers: if you look at the issues here, many have commits referring to them. These commits are actually referring to the issue in _my_ issue tracker. D'oh. Not sure where to go from here.

So far my plan is to close all issues concerning rendering/site-specific/crash problems, since they're almost certain to be no longer relevent, and people can reopen them if they're still an issue. I'm guessing that'll get rid of at least half the issues. If you'd like to help out with that, go for it, and thanks! Issues about follow mode can be closed too; that's been completely reimplemented.

**Comment by groolot** [comment]
Without permissions I cannot close anything, nor editing to assign a label.

**Comment by aidanholm** [comment]
You should have write access to luakit/luakit now, which will allow you to do both of those things (everything in the Write Permissions column [here](https://help.github.com/articles/repository-permission-levels-for-an-organization/).

**Comment by groolot** [comment]
I don't see any changes in my permissions on the repository. Is it on your own repo or this one?

**Comment by aidanholm** [comment]
This one; you may have to check your email, as it's an invite.
