### ISSUE TITLE
Open hints with external program

### ISSUE THREAD

**Issue by Asm1r** [luakit/luakit#415]
Greetings.

Basicaly I've been trying to add a keybind to open video links with mpv player but I can't really figure it out.
The old wiki method seems deprecated, is there a new way to do it?

Thanks

**Comment by aidanholm** [comment]
Hey,

Generally, external applications can be spawned with `luakit.spawn(command)`. You could bind a key in `normal` mode to get the current/hovered URI and spawn "mpv {uri}" (or some other command that enqueues videos, possibly).

You could also bind a key in `ex-follow` mode to use hints---there's a bunch of different bindings for that already set up near the bottom of `lib/follow.lua`, so it'd be fairly easy to see how to add your own. If you go this route, your selector and evaluator would both be "uri", and you should add the bind in `rc.lua` rather than modifying `follow.lua` directly.

Hope that helps, and I'm happy to clarify if needed; by the way, which wiki page were you referring to?

**Comment by Asm1r** [comment]
That was easy, thank you!

And the wiki page is [this one](https://github.com/luakit/luakit/wiki/Play-embedded-video-in-external-player.)

**Comment by aidanholm** [comment]
You're welcome!
