### ISSUE TITLE
User's bindings lost since ae71dae3ae4545fde6e9a20d0364a56fed8dbb76 ; distribution bindings preempt

### ISSUE THREAD

**Issue by groolot** [luakit/luakit#423]
Since the commit ae71dae3ae4545fde6e9a20d0364a56fed8dbb76, my user bindings writen in ~/.config/luakit/binds.lua are not active anymore, even if my rc.lua is loaded, parsed and used correctly.

The murder commit was find with the git bisect method.

**Comment by groolot** [comment]
Then the last good version for me is the bb234a65.

**Comment by aidanholm** [comment]
Hey @groolot!
I've changed the way bindings are changed. You don't need to keep a copy of the full binds.lua any more; instead, add/remove the binds you want from `rc.lua` or another file. Also, there's a slightly different API. Instead of using `key()`, `buf()`, etc., you use a string:
```lua
modes.add_binds("normal", {
   { "<Control-a>", "optional description", function () ... end },
   { "abcd", "this is a buffer binding", function () ... end },
})
```
Sorry for the trouble, and let me know if you have any difficulties!
