### ISSUE TITLE
Errors in user-defined rc.lua don't show up in log

### ISSUE THREAD

**Issue by jonas-schievink** [luakit/luakit#467]
To reproduce, simply make `~/.config/rc.lua` cause an error.

luakit logs the error to the console:

```
[    0.228536] E [core/common/lualib]: Lua error: aaaah!!!
                 Traceback:
                 ...
```

Since luakit will fall back to `/etc/xdg` in this case, it still seems to work, and there's no trace of the error in `luakit://log`, except that the message `Loading rc: /etc/xdg/luakit/rc.lua` now refers to the system `rc.lua`.

(I'm using the current `develop` version via the AUR package)

**Comment by aidanholm** [comment]
I'm not sure how easy this will be to do something about. If your custom config is breaking, the ideal fix is to fix the config, but I guess there's no real indication of the fallback, other than a slower start up time and none of the users settings loading.

This isn't easy to fix because luakit reexecs itself to load the fallback config. About the only way is to log a warning on start up that it's fallen back; that should be easy enough to do.

**Comment by aidanholm** [comment]
This is fixed; thanks for reporting!
