### ISSUE TITLE
forms input ; tab

### ISSUE THREAD

**Issue by parisni** [luakit/luakit#478]
Hey

I switched from 2015 version (ubuntu apt version) to the last github release.

I am not able able to go to next input when filling a form by typing "tab" or "Shift+tab"

Is this the normal behavior, I can read in the documentation that this should work

**Comment by ghost** [comment]
No, this is not normal behavior. It was a bug that has been fixed with https://github.com/luakit/luakit/commit/e5f1d320026aebc8e6148f116a71783693241650. So it should not occur in the current 2017.08.10 release. It also should not happen if you compile luakit from the `develop` branch.

EDIT: see below, the bug exists in the 2017.08.10 release!

**Comment by aidanholm** [comment]
Actually, e5f1d32 caused that bug; it was fixed with the revert of that commit at b22be9de, which is on `develop` but hasn't been included in a release yet.
