### ISSUE TITLE
Funny search path for web modules

### ISSUE THREAD

**Issue by hofheinz** [luakit/luakit#508]
I'm trying to load a custom (i.e., per-user, not system-wide) web module with `require_web_module("foo_wm")`. This command appears to look for `foo_wm.lua` and `foo_wm.so` in various system-wide locations (such as `/usr/local/share/luakit/lib/`) _and_ in the current working directory (i.e., in `./`).

However, it seems hard to have this command find a web module in, say, `$HOME/.config/luakit/`. (`require` seems to allow such a thing for modules.) In fact, neither `require_web_module("/absolute/path/to/foo_wm")` nor `require_web_module("relative/path/to/foo_wm")` appears to work. (Tested under Linux and OpenBSD with the current `develop` version.)

Is it intended to allow web modules somewhere in, say, the user's `$HOME` hierarchy? (Personally, I would think this is a useful thing, but maybe there are, e.g., security concerns. BTW, if having this is not intended, then it would probably be useful to remove the `./` search path, since this allows custom web modules to a certain extent anyway.) I could not track down where exactly those paths are defined, but I'd be happy to try to implement this if pointed in the right direction.

**Comment by aidanholm** [comment]
Sorry for the delayed response. The web extensions have the same default `package.path` as the main UI lua instance, and `require_web_module()` is just a proxy for `require` on the web process. So loading web modules from `~/.config/luakit/` should work just fine. I'll test it myself and get back to you.

Re security concerns; web modules are only slightly more capable of "doing bad things" than regular UI modules. It's sort of assumed that luakit has a safe environment in which to run. `./` should only be present in the search path if you're running a build with `DEVELOPMENT_PATHS=1`.

For users wishing to lock down their `package.path` in order to ensure that random modules from their filesystem aren't loaded, the bad news is that `package.path` isn't synced between UI and web processes. When a new web process is started, its default `package.path` is set to the luakit default, even if the UI process `package.path` has been modified in `rc.lua`. That's something that might be good to change.

**Comment by hofheinz** [comment]
Thanks for your answer! I played a bit around with `package.path`. It seems that `require` respects `package.path`, while `require_web_module` does not (at least not when I try to change `package.path` in `rc.lua`). The value of `package.path` when reading `rc.lua` is
```
./?.lua;/usr/local/share/luajit-2.0/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/share/luakit/lib/?.lua;/usr/local/shar$
```
(I compiled without `DEVELOPMENT_PATHS=1`, and the `CFLAGS` value from the make file output suggests it's really not there.) The search path for `require_web_module` includes only system directories; this is the output after a `require_web_module("my_web_module")`:
```
[    0.586577] E [core/common/lualib]: Lua error: module 'my_web_module' not found:
                        no field package.preload['my_web_module']
                        no file './my_web_module.lua'
                        no file '/usr/local/share/luajit-2.0/my_web_module.lua'
                        no file '/usr/local/share/lua/5.1/my_web_module.lua'
                        no file '/usr/local/share/lua/5.1/my_web_module/init.lua'
                        no file '/usr/local/share/luakit/lib/my_web_module.lua'
                        no file '/usr/local/share/luakit/lib/my_web_module/init.lua'
                        no file '/etc/xdg/luakit/my_web_module.lua'
                        no file '/etc/xdg/luakit/my_web_module/init.lua'
                        no file './my_web_module.so'
                        no file '/usr/local/lib/lua/5.1/my_web_module.so'
                        no file '/usr/local/lib/lua/5.1/loadall.so'
```

Regarding security: I thought so, and was just looking for a possible explanation. (And yes, I'd completely agree that the user is responsible for his/her configuration.)

**Comment by aidanholm** [comment]
I've pushed an update that syncs `package.path` and `package.cpath` to web processes. It'll only happen when web processes are first open (hooking assignments to `package.path` can't be done in a non-hacky manner), so you should set those paths before creating any webview widgets, or loading any modules that create any.

**Comment by hofheinz** [comment]
Thank you, this works nicely! Now the search paths for modules and web modules are the same (and include `$HOME/.config/luakit` by default, even without explicitly setting up `package.path` in `rc.lua`). (I'm closing the issue then.)
