### ISSUE TITLE
The webinspector does not work

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#512]
Pressing F12 issues a GTK accessibility warning. Pressing it again open a blank window titled "Web inspector".

`git bisect` leads to the commit 87a2307041a5bc65c009a9ffe9991f992395b53a.

**Comment by aidanholm** [comment]
I can't reproduce this. When I press F12 on 87a2307, I get this warning, but the inspector opens after about a second:
```
Allocating size to WebKitWebViewBase 0x5653e2a7a680 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
This warning indicates an issue with WebKitGTK code, not luakit, and epiphany emits the same warning.

It's also 'impossible' for that commit to have broken the inspector...

What version of WebKitGTK are you using? Have you updated recently?

**Comment by ghost** [comment]
I'm using webkit2gtk v2.16.6 (the latest version on arch repos).

The issue is solved when I revert the changes on this property: `["webview.allow_universal_access_from_file_urls"]`, but then it issues a warning saying that the changed property doesn't exist.

Also, I just found out that if I press F12 before the page is fully loaded, the inspector shows up.

I'm going to see how I could have created this problem and report back later.

**Comment by aidanholm** [comment]
Ah, right, I can reproduce this now---thanks for reporting! The issue is the `webview.enable_developer_extras` setting, with a default value of `false`. The incorrect settings names which that commit fixes cause an error (not a warning), which interrupts the application of settings at page load, preventing developer extras from being disabled. If you fix the settings names, then developer extras are disabled on page load, breaking the inspector.
