### ISSUE TITLE
How can we support you?

### ISSUE THREAD

**Issue by leshy** [luakit/luakit#562]
Hi,
Now that vimperator development has stopped, I'm guessing you'll get a big influx of new users,

I'd like to support your development (especially in the light of vimperator development I think there might be others as well) but for now I can't invest any dev time myself, maybe it would be nice if you had a patreon page?;

Thanks!

**Comment by Plaque-fcc** [comment]
Hi, 

  What about Vimium?

On October 16, 2017 3:45:11 PM GMT+03:00, lesh <notifications@github.com> wrote:
>Hi,
>Now that vimperator development has stopped, I'm guessing you'll get a
>big influx of new users,
>
>I'd like to support your development (especially in the light of
>vimperator development I think there might be others as well) but for
>now I can't invest any dev time myself, maybe it would be nice if you
>had a patreon page?;
>
>Thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/luakit/luakit/issues/562

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aidanholm** [comment]
Hi!

While I'm very grateful for the thought, I'm not currently ready to accept donations for working on luakit, for a few different reasons.

First, there are many contributors to luakit, with more and more newer contributors recently. If I accepted donations, even in a general non-luakit context, a donation to me would be a de-facto donation to luakit, and I don't feel comfortable accepting donations on behalf of luakit when all other contributors would get nothing.

Second, I work on luakit mostly because I enjoy it, and it's not terribly demanding. That said, there are enough tasks on the todo-list already; adding an official luakit donations mechanism would add a lot of additional complexity: there'd be accounts to administrate, policy to decide on, etc. etc. This would push luakit into being more like work than fun.

If you'd like to support development, but don't have the time or the expertise to contribute code, the best way to help out is by opening an issue for any bugs you find or feature ideas you can think of. A great way to help is to open an issue for any questions you have, as this usually indicates areas where the documentation is lacking.

Thanks :)
