### ISSUE TITLE
Adblock possibly not loading rules

### ISSUE THREAD

**Issue by maca** [luakit/luakit#573]
Hi, 

I tried using the adblock module on a fresh luakit install ,with the rules from easylist as suggested by the documentation. But no blocking is performed and the rules are possibly not loaded. I am attaching a screenshot of the adblock chrome page.

Steps to reproduce:
- I installed luakit from the aur luakit-git package
- launch luakit to generate `~/.local/share/luakit` dir
- quit luakit
```
$ cd ~/.local/share/luakit/adblock
$ wget https://easylist.to/easylist/easylist.txt 
$ luakit
```

![sel-2017-10-29--20 14 10](https://user-images.githubusercontent.com/29857/32147411-20c5a082-bce7-11e7-9cb9-1519fa2dd243.png)

**Comment by aidanholm** [comment]
This is caused by the subscriptions file not working correctly (not sure why...). To work around this, create a file `~/.local/share/luakit/adblock/subscriptions` with the line `easylist.txt\t\tEnabled` in it, except replace `\t` with a literal tab; so the name of the file, then two tabs, then "Enabled"

**Comment by maca** [comment]
@aidanholm 

Thanks! that worked, the file was empty before

**Comment by aidanholm** [comment]
Thanks for reporting the issue; all fixed!
