### ISSUE TITLE
Single-window no-tabs setting (with domain specific support!)

### ISSUE THREAD

**Issue by aidanholm** [luakit/luakit#575]
Suggested by @xkpd3 in IRC :tada:

 - with this setting enabled globally, each instance of luakit can only have a single tab in a single window
 - with this enabled on a per-domain basis, if you already have a tab open for site, `:o` will affect the already-open tab
  - what about `:w`, `:t`, etc?

**Comment by Ygrex** [comment]
I practically do this in `binds.lua` (actually in `userconf.lua` with more code duplication but the same idea):
```
-                    w:new_tab(uri, { switch = false, private = w.view.private })
+                    require("window").new({uri})
```

Not as elegant as the actual single-window support would bring, but suffice my needs. Multi-tabbed interface is rather annoying in tabbed WMs (I use Notion to be specific).

**Comment by c0dev0id** [comment]
For the record, I am/was xkdp3 (my former gh nick before MS bought this thing thing and I deleted my account and all original repos). Anyway... I solved it the same way and it's absolutely "good enough". Together with "hide when only one tab" it suits a tiling WM perfectly.

**Comment by c0dev0id** [comment]
When I'm thinking about per domain basis desicions if a new tab or a new window shall be used, I think this is too much of an edge case. Lua is flexible enough to hack a good enough solution for these cases. Not everything needs to be solved by core luakit.

I'm closing it, because I don't really want to persue this feature. If @aidanholm or anyone else wants this, please reopen it. (or say so and I reopen it...)
