### ISSUE TITLE
noscript domain matching issues

### ISSUE THREAD

**Issue by arcnmx** [luakit/luakit#649]
There are a few scenarios where noscript seems to act strangely with domain overrides (unexpected behaviour bolded):

1. `:open` seems to match against the previous open url/domain
    1. `noscript.enable_scripts = false`
    2. starting from `about:blank`
    3. `:open domain.com` where `domain.com` is set to override and allow scripts
    4. **`domain.com` opens without executing scripts**
    5. `:reload`
    6. scripts now work
2. `,ts` toggle scripts on seems to require two refreshes to take effect
    1. `noscript.enable_scripts = false`
    2. navigate to site that uses javascript but has no overrides set
    3. thus no scripts execute
    4. `,ts` to toggle scripts on
    5. `:reload`
    6. **page loads again without executing scripts**
    7. `:reload`
    8. scripts now work

**Comment by aidanholm** [comment]
It seems that you're mixing the noscript plugin with (domain-specific values of) the `webview.enable_javascript` setting. This won't work currently, as the noscript plugin has its own callbacks that it uses to control whether JS is enabled or not: these will race with the callback that adjusts JS according to the domain-specific setting.

The plan is to move noscript to use the APIs for persisted settings; then all the actual script enabling/disabling would be done by the webview module, and noscript would just provide convenience bindings and a statusbar widget.

**Comment by arcnmx** [comment]
Not sure I follow where `webview.enable_javascript` is coming from? That's certainly not used anywhere in my config - the `noscript` plugin provides the `,ts` bindings itself and handles the domain-specific overrides inside the plugin, so there should be no conflicts here?

The issue seems to be pretty consistent, and I'm reproducing it just using the default rc.lua with `require("noscript").enable_scripts = false` added.

**Comment by aidanholm** [comment]
Ah, then I misunderstood you; I thought by domain overrides you meant setting domain overrides, not noscript rules. If you're not touching the `webview.enable_javascript` setting at all, then this is definitely a bug.

Incidentally I've noticed myself over the past few days that some page loads seem to result in a screenful of HTML tags rendered as text, which renders correctly after a reload; not sure if this is related.

**Comment by delister** [comment]
I confirm. I noticed what if go to site by `:tabopen` command, then it's ok. But if use `:open` command, then js scripts doesn't work for first time.

**Comment by balejk** [comment]
I am having this issue as well. Any ideas where to look for solution? I looked into the noscript module a little bit but wasn't able to see any problem there.

It is also worth noting that while the JS is disabled on page where it should be enabled when coming from a page where it is disabled, the opposite does not hold. That is, when `:open target` is run from a page where JS is enabled, it is *not* enabled on the `target` page. So it probably isn't an issue of the previous domain being matched (perhaps unless for instance only the *existence* of an override was checked against the wrong domain).

**Comment by c0dev0id** [comment]
I think there are several issues open that hint at the same problem. I think there's a sequence issue between when navigation requests are executed and when the configuration/settings are set. Sometimes the web resource seems to be loaded first, then the settings are applied. In this case, some things only work after a second navigation request (refresh). Or sometimes it works right away when a http->https redirect is hit, because these are two navigation requests right away.

I have not looked a this issue (but it bugs me too).

**Comment by balejk** [comment]
Stefan Hagen, 2024-02-25T22:59:02-08:00:
> I think there are several issues open that hint at the same problem. I think there's a sequence issue between when navigation requests are executed and when the configuration/settings are set. Sometimes the web resource seems to be loaded first, then the settings are applied. In this case, some things only work after a second navigation request (refresh). Or sometimes it works right away when a http->https redirect is hit, because these are two navigation requests right away.

I have tried to backtrack this again unsuccessfully. Based on some debug
prints which I have added to noscript.lua everything seems to be fine
there, but I wasn't able to identify where the stuff set in the noscript
plugin takes effect.

If I understand correctly, the key spot is the `v.enable_scripts = es`
line in `update_webview_blocking` which is invoked on `load-status`
`committed` signal. But I wasn't able to grep where this is read back
and the actual directive to disable the JS based on this is given. I
expect it somewhere in the luakit core C code, but could not find it.

Or is the `view` object on which `enable_scripts` is set an internal
WebKit thing exposed to Lua (and so the setting would be read there
instead of in Luakit)?

If you were able to point me to the spot where the JS is being executed
(or tell me that I'm going about it completely wrong), I would be happy
to continue trying to identify the issue, once I find some time again.

**Comment by balejk** [comment]
Additionally, trying to have `update_webview_blocking` execute on
`load-status` `provisional` instead of `committed`, which I assume is
emitted earlier, leads to all pages getting loaded without JS even when
the domain is allowed to execute it and even in those cases in which it
works with `commited` as mentioned in the issue description (so
`:reload` or new tab).

More curiously though, DuckDuckGo doesn't automatically redirect me to
the no-JS variant in this case as if it couldn't detect that JS is
disabled.
