### ISSUE TITLE
missing ex-follow evaluator_func?

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#650]
Hi,

I just upgraded from a really old version of luakit, got most of the configurations migrated, but I notice when adding a bind for ex-follow mode it does not handle evaluator_func. 

My goal is to get a link from video tag and play it using mpv. The few existing evaluators in core library "uri" and "src" didn't seem to work; src string attribute can be retrieved through element.attr.src but not element.src. Also I wanted to handle the case where src link is in source element.

I ended up adding evlautor_func in follow.lua and follow_wm.lua, but I am not sure what is the supposed way to approach this when this was taken out.

Thanks.

**Comment by aidanholm** [comment]
Hi!

I've just added support for `evaluator` to be a function. Instead of providing a string like `"uri"`, you provide a function that accepts two arguments (`element` and `page`) and returns the desired content. This function is serialized and then loaded in the web process, so it won't have access to any local scope.

Hope that helps!

**Comment by ghost** [comment]
Thanks!
