### ISSUE TITLE
Difference between "settings.example" and "settings.set_setting("example", ...)"

### ISSUE THREAD

**Issue by zappathustra** [luakit/luakit#660]
If you set a setting with:

```
settings.set_setting("example", "foo")
```

then you can still change it in the `:settings` page.

On the other hand, if you set it with

```
settings.example = "foo"
```

then it is greyed out, as I think it should be. This is all the more problematic as the second way of customizing settings is not the proper way; I think it should be deprecated, and the first way should be made to work properly.

On the other hand, since the second way is so much more convenient, perhaps a nice middle ground would be to be able to do:

```
settings.set_setting.example = "foo"
```

i.e. `settings.set_setting` could be a table with a metatable implementing `__call`.

**Comment by aidanholm** [comment]
The current APIs are a little confusing and work slightly differently, because they're intended to accomodate two different audiences: people who want to use rc.lua to change settings, and people who prefer a GUI or using the `:set` command.

These could probably be better documented, but here's a basic explanation:

### User API
```lua
settings.example = "foo"
```
This is the API that is intended for use in `rc.lua`. Settings set in this way are ephemeral, not persisted: if you remove the line from your rc, it will no longer be applied. They override any persisted value, which is why the settings page entry will be greyed out.

### Module API
```lua
settings.set_setting("example", "foo")
```
The `settings.get_setting` API and all functions in the `settings` module are for modules, and shouldn't be used in `rc.lua`. Settings set in this way are persisted: the `luakit://settings/` page uses this API to store settings values between restarts. If you use this in your `rc.lua` instead of the user API, deleting the line won't remove the setting, which will be confusing.

**Comment by zappathustra** [comment]
OK, this makes sense! By the way, by `rc.lua`, I suppose you mean `userconf.lua` :smiley: -- but really, `rc.lua` should be replaced by some `main.lua` module which loads every other module, don't you think? Users should be able to copy and modify it it if they really want to, but as I understand it now it's a pretty extreme operation, not something the average users should do.

Since we're talking configuration, the Luakit page on the Arch wiki is badly out of date. I updated it yesterday and then lost all my changes (still haven't made the "Edit in the external editor" thing work correctly...) so I just added a warning, but somebody should take care of that (I'll do it again if I find the time). The Arch wiki is quite popular, I believe (but then, I'm an Arch user, so I tend to believe such things!).

**Comment by zappathustra** [comment]
Ah, but: if `settings.example` is the way to go in user config, then isn't there a problem in that only `settings.set_setting` allows per-domain customization?

**Comment by aidanholm** [comment]
There's a lot of modules which are loaded by default that users might want to disable for whatever reason. My plan is to eventually replace rc.lua with some code which reads a list of modules to load and then loads them, doing dependency resolution automatically.

Yeah, I've noticed that about the arch wiki page, which is unfortunate :/

Per domain customization is `settings.on["foo.com"].webview.foo = "bar"`

**Comment by zappathustra** [comment]
I've updated the Arch wiki page to the best of my knowledge. Reviews and/or contributions are more than welcome!

**Comment by aidanholm** [comment]
Great; thanks!

**Comment by c0dev0id** [comment]
I think the questions here have been answered. Closing the issue.
