### ISSUE TITLE
How to start luakit for fullscreen?

### ISSUE THREAD

**Issue by sdamo** [luakit/luakit#696]
?

**Comment by aidanholm** [comment]
You can add this to your RC file; it'll automatically fullscreen new windows, which might be weird if you open more than one.
```lua
window.add_signal("init", function (w)
    w.win.fullscreen = true
end)
```

**Comment by sdamo** [comment]
@aidanholm version?

**Comment by aidanholm** [comment]
Not sure what you mean?

**Comment by sdamo** [comment]
For which version luakit?

**Comment by McSinyx** [comment]
Which for which version of luakit? Really, proper communication is important, you cannot just drop a few words and expect us to understand.

Does the init signal work for you? If the instruction was unclear, then the per-user RC file is default to `~/.config/luakit/rc.lua`, just copy the global one if the file doesn't exist. If this doesn't work for you because your luakit is dated, please, update to a newer one (you could do some search and blaming to find out which version first supported the feature, but trail is always faster).

**Comment by sdamo** [comment]
OS Ubuntu 17.10 default package version 2012.09.13-r1-8

This not work:
```
window.add_signal("init", function (w)
    w.win.fullscreen = true
end)
```
And need method fullscreen after start luakit.

PS Русские есть?

**Comment by sdamo** [comment]
Not work =)

wget https://github.com/luakit/luakit/archive/debian/2017.08.10.zip
unzip 2017.08.10.zip
cd luakit-debian-2017.08.10
dpkg-buildpackage
sudo dpkg -i ../luakit_2017.08.10_amd64.deb
cp /etc/xdg/luakit/* ~/.config/luakit
cat >> ~/.config/luakit/rc.lua
```
window.add_signal("init", function (w)
    w.win.fullscreen = true
end)
```
luakit -V
`luakit 2017.08.10`

Need fullscreen after start luakit. Can there is a way to send F11 after launch?

**Comment by sdamo** [comment]
This work:

```
for _, w in pairs(window.bywidget) do
w.win.fullscreen = true
end
```

**Comment by aidanholm** [comment]
I'm glad you solved your problem; for future reference. the code I posted won't work if you add it to the very end of the file. It has to be added before the `-- End user script loading --` commend. This is a common cause of problems. Sorry for the confusion!

**Comment by pepa65** [comment]
I am getting `no windows spawned by rc file, exiting`...
Actually even without any content in `~/.config/luakit/rc.lua` I get this. Only when I remove the file does luakit start working again, but not in full-screen mode...
