### ISSUE TITLE
Auto swich proxy depending on the URL

### ISSUE THREAD

**Issue by piyavking** [luakit/luakit#703]
Hello. 

I'm interested in the ability to bind a proxy to the URL, like the widespread Mozilla's extension "AutoProxy". As a person living in a totalitarian country, this is important enough for me. Maybe there is a user script that does this?

Thanks you for attention.

**Comment by aidanholm** [comment]
Hi!

Do you mean switch proxy automatically, based on the URL? Unfortunately this isn't possible with the APIs that webkit currently exposes. There is a proxy switching API, but switching proxy based on the URL would have race conditions, since the network requests are sent from a separate process, and so inevitably some requests would be sent to the wrong proxy.

One approach that you might be able to use is to run a local proxy, send all traffic to that from luakit, and then switch based on the URL from that proxy.

**Comment by piyavking** [comment]
I understand. That's good idea, thanks!

And (returning to the original idea) maybe it's possible to make the corresponding lua script, which will switch the proxy not on the webkit level, but at the level of the luakit interface? Does it make sense for me to try to do this?

**Comment by aidanholm** [comment]
The luakit proxy interface uses the webkit API, and so can't be used in this manner. If you were switching proxies externally, it'd be possible to control that from luakit, sure; it'd just have to be separate from the proxy interface.

**Comment by piyavking** [comment]
Thanks!

**Comment by aidanholm** [comment]
You're welcome!
