### ISSUE TITLE
playing a youtube video crash

### ISSUE THREAD

**Issue by orendanniel015** [luakit/luakit#713]
after solving the last issue https://github.com/luakit/luakit/issues/712 I have tried to play the video it just crashes the current tab and I get a screen that informs me that "web process crashed"

What should I do?

**Comment by orendanniel015** [comment]
I found the sulotion:
in addition to installing the optional deps: gst-libav gst-plugins-good gst-plugin-base, I also installed gst-plugins-bad gst-plugins-ugly and it seems like it solved the problem

**Comment by CodeJoule** [comment]
I am having this issue as well. I have these packages installed on my system (FreeBSD):
```
gstreamer1-1.16.2
gstreamer1-libav-1.16.2
gstreamer1-plugins-1.16.2
gstreamer1-plugins-a52dec-1.16.2
gstreamer1-plugins-bad-1.16.2
gstreamer1-plugins-core-1.16
gstreamer1-plugins-dts-1.16.2
gstreamer1-plugins-dvdread-1.16.2_1
gstreamer1-plugins-gl-1.16.2
gstreamer1-plugins-good-1.16.2
gstreamer1-plugins-mpg123-1.16.2
gstreamer1-plugins-ogg-1.16.2
gstreamer1-plugins-pango-1.16.2
gstreamer1-plugins-png-1.16.2
gstreamer1-plugins-resindvd-1.16.2_1
gstreamer1-plugins-theora-1.16.2
gstreamer1-plugins-ugly-1.16.2
gstreamer1-plugins-vorbis-1.16.2
```
Since I also have `-bad` and `-ugly` installed, there must be something else causing this problem. Can someone help me with this? I am not *very* experienced with these packages or web development, but I am willing to work with someone to resolve this issue. Besides YouTube not working (and few other minor problems), LuaKit looks awesome!
