### ISSUE TITLE
How to set domain_props? Where is it?

### ISSUE THREAD

**Issue by alex3kov** [luakit/luakit#787]
## I'm submitting a…
Documentation Bug Report

## Current Behavior
I'm trying to set [domain_props setting](https://luakit.github.io/docs/modules/domain_props.html)

## Expected Behavior
domain_props being set and luakit starting up

## Reproduction Instructions

1. Putting this (according to docs) into ~/.config/luakit/userconf.lua:
```
globals.domain_props = {
    ["all"] = {
        enable_scripts = false,
        enable_plugins = false,
    },
}
```
Luakit doesn't start with `[    0.220121] E [core/common/lualib]: Lua error: attempt to index global 'globals' (a nil value)`
2. After reviewing #440 , trying this:
```
local settings = require "settings"
settings.webview.domain_props = {
    ["all"] = {
        enable_scripts = false,
        enable_plugins = false,
    },
}
```
Luakit doesn't start with `[    0.218717] E [core/common/lualib]: Lua error: cannot assign a value to invalid setting path 'webview.domain_props'`
## Environment
Linux Distribution & Version: Parabola, rolling
Output of `luakit --version`:
```
luakit fc07ed5a
  built with webkit 2.24.1 (installed version: 2.24.1)
```

**Comment by c0dev0id** [comment]
Hi,
the syntax was changed with the refactoring to support the `:settings` page.

In the rc file, you can set domain specific properties like this:
```
settings.on["youtube.com"].webview.enable_javascript = true
```

I think the documentation is out of sync here... :/

**Comment by alex3kov** [comment]
@c0dev0id so domain_props thing doesn't even exist anymore? How would you achieve the same functionality with that new syntax then (whitelist only several websites for JS)?

**Comment by aidanholm** [comment]
It doesn't exist, no. Well, there is a shim for it, but it's loaded before userconf.lua, which is why it doesn't help here.

I'd suggest using the noscript module:
```lua
local noscript = require "noscript"

noscript.enable_scripts = false
noscript.enable_plugins = false
```

Noscript adds some keybinds to toggle settings on a per-site basis (`,ts`, `,tp`, `,tr`) that should also be viewable on `luakit://binds/`. Hope this helps, and thanks for reporting the documentation issue :)

**Comment by alex3kov** [comment]
@aidanholm That sounds horrible, so the only way to do this is to press keybinds all the time? I want a static list of allowed webistes in the config file (or some other file). Was that functionality torn away from Luakit completely along with `domain_props`?

**Comment by aidanholm** [comment]
The module stores domains in a sqlite database at `~/.local/share/luakit/noscript.db`. The keybinds are a convenience for quickly editing that database, since a few keystrokes is preferable to editing a config file and then restarting the browser, but you can edit that database any way you want. If you prefer a file with a flat list of domains, it'd be reasonably straight-forward to auto sync that to the db, or you could also just write a custom noscript module based on the existing one.

**Comment by alex3kov** [comment]
@aidanholm Ah, so those settings are persistent, that's good to hear. No, I don't need a flat file specifically - any form of viewable and editable persistence will do (domain look ups in the DB are also faster, I would imagine?).  
I checked `luakit://binds/` page - can't find those `,tr`, `,tp`, `,tr` bindings anywhere. [noscript](https://luakit.github.io/docs/modules/noscript.html) API page also doesn't mention them. So please document them somewhere if you don't mind :)

**Comment by aidanholm** [comment]
Ah, yeah, having to toggle your settings after every restart would get annoying really quickly.

Is the noscript module enabled? That page only shows the binds that are currently loaded, since binds are registered by the module; they're not declared separately. `,ts` toggles noscript status for the current domain, `,tp` does the same, but for plugins instead of javascript, and `,tr` removes rules (both plugins and scripts) for the current domain. The difference between disabling via `,ts` and removing rules has an effect if you change the default setting later (`noscript.enable_scripts = whatever`) afterwards: if you remove rules with `,tr` then change the default, the new default will be used. I almost always just use `,ts` myself.

The default keybind is a bit awkward, but it's not too commonly used; if you want to remap it, that's also possible.

**Comment by alex3kov** [comment]
OK, after enabling noscript these bindings appeared in `luakit://binds` page, thanks. Do you want me to try and make a PR documenting these bindings on noscript page or would you prefer to do it yourself? I can also rip out [this page](https://luakit.github.io/docs/modules/domain_props.html) while I'm at it :)

**Comment by aidanholm** [comment]
PRs are always welcome :) I'll handle the domain_props stuff myself since I should really just remove that stuff entirely.

**Comment by alex3kov** [comment]
I can see that bindings appear on luakit://help/doc/modules/noscript.html page after activating noscript (did I not notice them before or is that page being pulled from Internet?)
