### ISSUE TITLE
Build fails during linking

### ISSUE THREAD

**Issue by nedludd** [luakit/luakit#853]
## Can't build luakit, many `multiple definition of`  errors during linking

Errors are here:  https://gist.github.com/nedludd/6cacc55ffdf3628cb336b242ea31d9c5

## Environment

Linux Distribution & Version:  Arch Linux - latest

**Comment by msdemlei** [comment]
I suppose that's compiling with gcc 10?  If so, can you see of PR #837 fixes your problem?

**Comment by nedludd** [comment]
Closer, now we're just down to errors with extensions:

https://gist.github.com/9ae40f097136b41f2edb69c44cafe136

**Comment by msdemlei** [comment]
On Mon, Jun 08, 2020 at 12:14:41PM -0700, Ned Ludd wrote:
> Closer, now we're just down to errors with extensions:
> 
> https://gist.github.com/9ae40f097136b41f2edb69c44cafe136

Ah... Missed that global (sorry -- I can't be bothered to set up a
chroot with gcc 10 just yet).  This one ought to be fixed in the PR
now.

[disclaimer: there are failing tests in the branch that I don't have
time to investigate now but that are probably unrelated to the gcc-10
patches; if things turn out not to work once it builds, it's probably
not your fault]

        -- Markus

**Comment by aidanholm** [comment]
I've merged that PR and things seem to be working fine for me; let me know if there are further issues!

**Comment by nedludd** [comment]
Yup!  Looks good.  Thanks guys!
