### ISSUE TITLE
Block cursor in input bar

### ISSUE THREAD

**Issue by ghost** [luakit/luakit#859]
The default cursor shape in the input bar is a blinking bar.  Would it be possible to change the shape to a block cursor and remove the blinking, with the current modules?

**Comment by c0dev0id** [comment]
The input bar is styled with CSS. It's not possible to influence the blinking or the cursor style. GTK shows no way to do this. Unfortunately. I would have liked a block cursor there myself :(

I think the reason is, that the block cursor is kind of reserved to indicate that you're in overwrite mode. While in the input bar, you can press "insert" on the keyboard. This switches to a block cursor - but also into overwrite mode.

I'm closing the issue => cannot be done. At least not with the current gtk framework.
