### ISSUE TITLE
how to set up luakit as kiosk browser

### ISSUE THREAD

**Issue by gearhead** [luakit/luakit#903]
Running arch linux on rpis. I want/need a single full window tab and need to display the localhost which is a php/js page. I am running matchbox wm. I can get it to display the google search page http:/www/google/com. When I try either http://localhost or http://127.0.0.1 all I get is a white page. In the text line at the bottom of the screen it says (notrust) in red. No amount of refreshing does anything useful. This is with webkit2gtk 2.30 and luakit 2.2.1

I just tried to go to luakit://settings and get the same result: A white page with nothing in it. Seems like something is missing. Strange that google shows up... If I load news.google.com, I can select in the blank page and a new window opens up which is also blank but the tab has the title in it. 

The journal shows a couple of dbus errors:
```
Mar 03 22:48:01 runev7 dbus-daemon[306]: [system] Rejected send message, 4 matched rules; type="method_call", sender=":1.1677" (uid=33 pid=1530 comm="/usr/lib/webkit2gtk-4.0/WebKitNetworkProcess 3 12 ") interface=">
Mar 03 22:48:01 runev7 xinit[1504]: [    0.911268] I [lua/styles]: found 0 user stylesheets
Mar 03 22:48:03 runev7 xinit[1504]: [    2.542370] I [lua/webview]: Requested link: http://localhost/ (text/html)
Mar 03 22:48:03 runev7 xinit[1542]: libEGL warning: DRI2: failed to authenticate
Mar 03 22:48:04 runev7 xinit[1542]: Could not create EGL sharing context.
Mar 03 22:48:04 runev7 xinit[1542]: Could not create EGL context.
Mar 03 22:48:16 runev7 xinit[1504]: [   16.076037] I [lua/webview]: Requested link: http://127.0.0.1/ (text/html)
Mar 03 22:48:17 runev7 xinit[1541]: libEGL warning: DRI2: failed to authenticate
Mar 03 22:48:17 runev7 xinit[1541]: Could not create EGL sharing context.
Mar 03 22:48:17 runev7 xinit[1541]: Could not create EGL context.
Mar 03 22:48:30 runev7 dbus-daemon[306]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30006ms)
```
I do not think the EGL warnings are of consequence. 

Also am unsure of how to make it a single tab without the text at the bottom of the page and full screen, but first I need to be able to display my localhost. Any help appreciated.

**Comment by taobert** [comment]
A kiosk  mode has been asked about in #225 and #741.
Did the suggestions in #225 not help?
Luakit's fullscreen mode (accessable by pressing `F11`) by default hides both the tab and status bars.
It's still possible to make new tabs, via keybindings/command mode, but you could probably disable these bindings.
(Will your users have a keyboard?)


Regarding the `dbus` errors,  i can't really help much.
I'd suggest that you look into the `4 matched rules` metioned,
but those lines don't seem to be repeated with each navigation,
so it's not clear to me that they're even relevant.

I assume that by `http:/www/google/com` you mean `http://www.google.com`.
Can you clarify what you mean by "If I load news.google.com, I can select in the blank page"?
What do you see if you do `:viewsource`? `:inspect`?

That you can't even get to luakit://settings is somewhat ponderous,
i would have expected that to be handled internally.
Am i correct in assuming that you cant get other internal pages (eg `luakit://help`)?
Are other browsers able to access http://localhost or http://news.google.com?
Particularly other webkit browsers like Epiphany.

Are you using a proxy? Firewall?
Is `localhost` in your `/etc/hosts` file? 
Is it generally true that internetty sites (http://en.wikipedia.org, http://xkcd.com) are accessable to you,
and that local ones are not? 
What happens when you hack your `/etc/hosts` and point `www.google.com` to `127.0.0.1`,
or to whatever your lan ip is? 
What's in `/etc/resolv.conf`?

**Comment by gearhead** [comment]
Thanks for taking the time to respond. The problem I am having, I believe, is a specific Arch Linux Arm problem. It is not just luakit, but most of the webkitgtk based browsers just show a white page when it tries to access EGL under X. I am trying to get it resolved through Arch as I think it crept in with the change from 5.4.x to 5.10.x

As for f11 and such. We want to launch it as a front end display w/o keyboard.  It would be awesome if zoom and full screen could be called at launch. ie. /usr/bin/luakit --fullscreen --zoom=0.7... Is this even possible? Midori used to do this (also gtk based) but all current versions from v5 or v6 do not. They are currently at v9. I love luakit and I think it would be great for our particular use, especially with these flags...

**Comment by taobert** [comment]
Well, confirming that it's Arch specific might be helpful.
Can/have you tried Raspbian?

I'm not familiar with Arch/dbus-daemon/EGL/DRI2,
and so the (many) questions i asked were largely spitballing,
but it'd be good to get answers to them.

I'm particularly interested in your phrase `I can select in the blank page`.
If you were able to click links in the page even though it all appears white,
(or if you get html in `:viewsource`/`:inspect`/`:dump`),
then it would seem to be a rendering issue rather than something networky.
(This would be consistent with the internal `luakit://` uris not displaying.)
Indeed, the EGL errors seem to correlate to navigation in the log.
Given that DRI is an initialism of Direct Rendering Interface,
your assumption that `I do not think the EGL warnings are of consequence` may be incorrect.
The quick google i just did found [a core-electronics post](https://forum.core-electronics.com.au/t/libegl-warning-dri2-failed-to-authenticate/7804)
which suggests that this could plausibly happen if the software distribution predates the hardware.
So, what version of Arch are you using, and what version of RPi?



There is not (to my knowledge) a command line flag for fullscreen (or zoom).
The other issues i linked to have suggestions about how to start in fullscreen mode by setting it in the startup files.
I think zoom could be also be set here.

In addition to no keyboard,
bear in mind for that there's also a right click menu which may need to be disabled
if it contains options you don't want users to have.

**Comment by gearhead** [comment]
Yes, I was able to click in the white void and a new window would open. 
I came to this conclusion yesterday that the DRI errors are indicating where the problem may be. We do not get those errors under wayland/weston and it displays correctly under wayland/weston.
```
Mar 03 22:48:04 runev7 xinit[1542]: Could not create EGL sharing context.
Mar 03 22:48:04 runev7 xinit[1542]: Could not create EGL context.
```
When we get this error, it seems to be when it quits displaying anything. The google initial search page page and some other pages display fine, but after some browsing and clicking, we eventually get that error and only a white page. 

This is on an RPI 3B+ and my arch is up to date as of last week. Kernel and version of xorg is:
```
X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
Build Operating System: Linux Arch Linux
Current Operating System: Linux rune64 5.10.17-3-ARCH #1 SMP PREEMPT Wed Mar 3 16:26:04 MST 2021 aarch64
Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:1920x1080M@50,marg>
Build Date: 16 December 2020  11:52:03PM
```
Under raspbian (under xorg) luakit works as expected. Under Arch Arm and weston (not xorg), luakit works as expected.

**Comment by taobert** [comment]
Cool.
Well it seems then that a `NotOurBug` flag is appropriate,
and that you have some options that work,
so i'll stop thinking about it.
If you _do_ persevere with Xorg on Arch and get it working,
please add a comment detailing how,
in case that helps someone else who stumbles upon this issue.


If you need more help with the `fullscreen`/`zoom`/etc,
i'm happy to put some thought into that.

**Comment by gearhead** [comment]
I agree with the 'not our bug' flag. It would be nice if fractional scaling and fullscreen could be selected at launch...
Most scaling is 2 or 3 (make it bigger for high dpi screens), but for us, we need 0.5, 0.7 (make it smaller) to fit it on a small screen and setting one or both at launch would be awesome. Thanks for the help!

**Comment by taobert** [comment]
Have you looked at the other issues i linked to in my first comment?
The earlier one details starting in fullscreen mode.
I would expect that this, along with the `webview.zoom_level` option in `luakit://settings`, would do what you need.
Am i misunderstanding?

**Comment by gearhead** [comment]
the 'white screen' and egl errors was due to not allocating enough memory and also not using the correct dtoverlay.
on my B3+, the config should have:
```
# kms
dtoverlay=vc4-kms-v3d
# memory options
gpu_mem=256
```
I had gpu_mem set at 16 and that was inadequate, causing the white page and egl errors. 

I was able to create a .config/luakit/userconf.lua file with this in it and get zoom level to 'stay'
```
local settings = require "settings"
settings.webview.zoom_level = 40
```
By the way luakit works under either Xorg or Weston/Wayland. 
thanks for the help! Sorry for the distraction.

**Comment by taobert** [comment]
The white screen may be the same issue as #773.
