### ISSUE TITLE
Edit URL in external editor

### ISSUE THREAD

**Issue by fedoranvar** [luakit/luakit#927]
Want to add binding <Control-e-u> to edit current URL.

But get stuck: which module and functions should i usefor this?

thank you!

**Comment by taobert** [comment]
Well, i'm not _quite_ sure what you're wanting to achieve as an end goal.
To be explicit, you're looking to edit the URL, rather than the page text/source?
And you then want to pass that back to Luakit to open the edited URL?

The `editor` module (luakit://help/doc/modules/editor.html) will edit an arbitrary file and then call a callback on exit,
so you can write the current uri (`w.view.uri`) to a file and call the editor with a callback to navigate to that page (`w:navigate(uri)`).
Note also:
- `y` will yank the current URL into the primary X buffer (or `Y` into the clipboard),
    and you can then paste it into your editor.
- `shift-o` will give you a new `:open ...` command at the bottom with the current URL filled in. 
    This input has some readlineish bindings for jumping about, and munging text.

**Comment by fedoranvar** [comment]
@taobert 
I think that's what i need! 

thank you!
