### ISSUE TITLE
Close multiple tabs from rofi (dmenu)

### ISSUE THREAD

**Issue by fedoranvar** [luakit/luakit#928]
i've got this script for focusing tab:

```
...
    { "<Alt-Tab>", "List tabs in rofi",
        function (w)
            local list = ""
            -- local cmd='rofi -dmenu -i -l 20 -theme ~/.config/rofi/launcher.rasi '
            local cmd='rofi -dmenu -i -l 20'
            local label
            local lousy = require 'lousy'

            for i, view in ipairs(w.tabs.children) do
                label=( (view.title ~= "Web Process Crashed" and view.title)
                    or view.uri
                    or "" )
                list = list .. i ..  "  " ..  label .. "\n"
            end
            list = lousy.util.escape(list)

            local fh=io.popen("echo '" ..list .. "' |" .. cmd ,"r")
            local sel=fh:read("*a")
            local tabchoice = string.match(sel, "^[0-9]+")

            if (tabchoice) then
                w.tabs:switch(tabchoice)
            end
        end
    },
    ...
```

For multiselect in rofi I can use 
``` 
local cmd='rofi -dmenu -i -l 20 -multi-select '
```

But which function i should use for closing tabs?

thank you!

**Comment by taobert** [comment]
So, i don't want to be unduly standoffish, but if you look at `:binds`/`luakit://binds` you'll see the file and line number where each binding's defined. So if you know a binding that does something like what you want (`^W` closes the current tab), you can find out fairly easily where, and therefore how, things are implemented.
There's also an auto-generated (read: roughly up-to-date) api at `luakit://help/doc/index.html`. (Edit: `close_tab` is missing from the `window` api because of some shenanegans which i don't understand, and am fairly sure i don't approve of.)
These and others are linked to from `:help`/`luakit://help/`.

If you do genuinely need more guidance i'm happy to provide it, but you have the source,
so asking the interwebs "Which function does X" is almost always going to be a slower way to get that information than grepping and thinking critically.

**Comment by fedoranvar** [comment]
Thank you! For some reason i don't have api doc  (`Opening /usr/share/luakit/doc/index.html failed` - Void Linux)

Thanks for the help - will try to get better!

**Comment by taobert** [comment]
There's also a copy of the api docs [online](https://luakit.github.io/docs/).
I should have included that link, though note that i was mistaken to point you towards them as `close_tab` isn't mentioned in them. (So i've edited my post.)
