### ISSUE TITLE
How can I disable javascript?

### ISSUE THREAD

**Issue by jgarte** [luakit/luakit#937]
Hi, how can I disable javascript in luakit?

**Comment by taobert** [comment]
Look at the `noscript` module.

**Comment by jgarte** [comment]
> Look at the `noscript` module.

I did but I'm not sure how to use it. 

Could you share an example snippet?

**Comment by taobert** [comment]
Luakit modules tend to be included in `rc.lua`.
The default `rc.lua` has the noscript inclusion commented out:
```
-- NoScript plugin, toggle scripts and or plugins on a per-domain basis.
-- `,ts` to toggle scripts, `,tp` to toggle plugins, `,tr` to reset.
-- If you use this module, don't use any site-specific `enable_scripts` or
-- `enable_plugins` settings, as these will conflict.
--require "noscript"
```

So you'll need to uncomment the `require "noscript"`.
(If you don't already have a personal `rc.lua` in `~/.config/luakit`, it should be copied from `/etc/xdg/luakit/`, rather than editing the system version).
Scripts are still on by default and need to be turned off on a per-domain basis. (The default bindings are mentioned in the `require ...` comment.) This stores choices to an sqlite3 database, so they persist across restarts.
If you want scripts to be off by default, change your `rc.lua` to have:
```
local noscript = require "noscript"
noscript.enable_scripts = false
```

**Comment by c0dev0id** [comment]
If you want to disable javascript for everything and permanently, you don't need the noscript module. In `:settings`, you can uncheck `webview.enable_javascript` and then javascript won't be evaluated any longer.

And as all methods have been mentioned now, I'm closing this issue.
