### ISSUE TITLE
complicated install on non-arch systems

### ISSUE THREAD

**Issue by ldelossa** [luakit/luakit#944]
**Current Behavior:**
Currently, its difficult to install luakit on non-arch systems. 

Most package managers are shipping lua > 5.1 and luajit attempts to find 5.1 packages.

Luarocks default installs will install 5.4 package, and you must compile your own luarocks app to install 5.1 

This is all a problem due to the depedency on lua-filesystem.

**Desired Behavior:**

RPM is created with dependencies including the lfs.so file copied into a 5.1 lua module search path. 

Some other installation package is provided for the drifting lua/lfs/luarocks problem.

**How can we reproduce it (step by step):**

Try to install luakit on Fedora 34. 

**Environment:**

Linux Distribution & Version: Fedora 34

**Comment by taobert** [comment]
Hmmmmm.

> Currently, its difficult to install luakit on non-arch systems.

Well, it installs fine for me using `make install` on Debian (Sid, luajit=2.1.0-beta3, lua-filesystem=1.8.0-1) so the title seems inaccurate to me.

> Most package managers are shipping lua > 5.1 and luajit attempts to find 5.1 packages.

I haven't comprehensively surveyed package managers, so i'll have to defer to your research RE what most of them have on offer. Debian ships lua 5.0-5.4, and lua-filesystem for 5.1-5.4.  

LuaJIT looks for 5.1 packages because it implements the lua 5.1 standard.
Luakit is written in lua 5.1, and recommends luajit because it's fast. Neither of these are likely to change in the immediate future.
If your distribution doesn't offer 5.1 then you may have to compile that yourself, though i see references to a `compat-lua-5.1.5-17.fc33.x86_64.rpm` package.

> Luarocks default installs will install 5.4 package, and you must compile your own luarocks app to install 5.1

I hadn't had luarocks installed. I just use the system lua packages.
Although now that i look into it, if a user installs luarocks on Debian they get it for 5.1-5.3. 
If your distribution doesn't offer 5.1 then you may have to compile that yourself.

> This is all a problem due to the depedency on lua-filesystem.

There is already an issue RE removing lfs (#429), and i have a [de-lfs-ed branch](https://github.com/taobert/luakit/tree/deprecate-lfs) which works fairly well, but which i never got around to PRing. I recently (a fortnight ago) had to correct it's mishandling of user stylesheet loading, so there may be other quirks which i haven't been bitten by yet, however if you feel lfs is central to your woes, i'd love it if you'd give it a test.

> RPM is created with dependencies including the lfs.so file copied into a 5.1 lua module search path

Even if there was a desire to retain lfs dependency in luakit, i feel that shipping it (or other third party bits) with luakit rather than requiring it as a dependency would be silly.

> Some other installation package is provided for the drifting lua/lfs/luarocks problem.

I don't think Lua 5.1 is going anywhere, anytime soon. Fedora choosing to not support lua < 5.4 is curious.
If your distribution doesn't offer 5.1 then you may have to compile that yourself.

**Comment by MuhammedZakir** [comment]
You can download pre-compiled binaries from https://sourceforge.net/projects/luabinaries/files/ [1].

Re: luarocks: compiling luafilesystem module: Even in an old computer I tried, compilation finished almost instantaneously.

[1] Mentioned under "Tools" in https://www.lua.org/download.html.

**Comment by ldelossa** [comment]
I'm an idiot. I didn't realize that there are "lua-5.1.*" rpm packages available in my repository. This should alleviate most of the issues of installing (and means I can get rid of luarocks, I'm not a lua user I just wanted to use this browser).

closing the issue, thanks for entertaining this.
