### ISSUE TITLE
Can't type in text boxes

### ISSUE THREAD

**Issue by chookity-pokk** [luakit/luakit#950]
**Current Behavior:**
Open any website with a text box (duckduckgo.com for this example) the try to type in there and the keybindings are overwriting what I am trying to produce. So if I type in `y` instead of putting `y` in the text box it yanks the URL.

**Desired Behavior:**
Being able to type into the text box or having keybindings recognize the behaivor

**How can we reproduce it (step by step):**
Pretty much described above

**Environment:**
Debian

Linux Distribution & Version:
Output of `luakit --version`:
Luakit 2.0

**Comment by c0dev0id** [comment]
When an input box is loaded and focused on page load, luakit is *not* switching to INSERT mode. This is, because you might want to navigate further and the mode switch would come as a surprise on many pages where the input field is not the main element like on a search page.

Either you type "i" to explicitly switch to INPUT mode, or you click on the input field again, which also should switch to the INPUT mode.

Side note: Your luakit is pretty old. This is not debian bullseye, is it?

**Comment by chookity-pokk** [comment]
That makes sense, maybe my phone was lagging and I clicked the text boxes twice which took me out on INPUT mode? Because I just tried and it worked so I will close this. 

Yeah, I am using Debian Bullseye on the [Pine Phone](https://www.pine64.org/pinephone/) using [Phosh](https://developer.puri.sm/Librem5/Software_Reference/Environments/Phosh.html). I just installed through `apt` earlier this week since my phone is underpowered so most browsers take forever to load but Luakit seems to load faster but isn't as responsive to touch.
