### ISSUE TITLE
[question] How to create a minimal configuration?

### ISSUE THREAD

**Issue by wsw70** [luakit/luakit#951]
I would like to use luakit in a kiosk mode on my home dashboard. I like the fact that the configuration is code driven but I fail to undesstand quite a lot of the details.

I start luakit as 

    luakit -u http://example.com

This opens **two** tabs with `http://example.com`

I tried to remove as much configuration as I could and ended up with:

```
------------------------------------------------------------------------------
-- luakit configuration file, more information at https://luakit.github.io/ --
------------------------------------------------------------------------------

require "lfs"

-- Check for lua configuration files that will never be loaded because they are
-- shadowed by builtin modules.
table.insert(package.loaders, 2, function (modname)
    if not package.searchpath then return end
    local f = package.searchpath(modname, package.path)
    if not f or f:find(luakit.install_paths.install_dir .. "/", 0, true) ~= 1 then
        return
    end
    local lf = luakit.config_dir .. "/" .. modname:gsub("%.","/") .. ".lua"
    if f == lf then
        msg.warn("Loading local version of '" .. modname .. "' module: " .. lf)
    elseif lfs.attributes(lf) then
        msg.warn("Found local version " .. lf
            .. " for core module '" .. modname
            .. "', but it won't be used, unless you update 'package.path' accordingly.")
    end
end)

require "unique_instance"

-- Set the number of web processes to use. A value of 0 means 'no limit'.
luakit.process_limit = 4
-- Set the cookie storage location
soup.cookies_storage = luakit.data_dir .. "/cookies.db"

-- Load library of useful functions for luakit
local lousy = require "lousy"

-- Load users theme
-- ("$XDG_CONFIG_HOME/luakit/theme.lua" or "/etc/xdg/luakit/theme.lua")
lousy.theme.init(lousy.util.find_config("theme.lua"))
assert(lousy.theme.get(), "failed to load theme")

-- Load users window class
-- ("$XDG_CONFIG_HOME/luakit/window.lua" or "/etc/xdg/luakit/window.lua")
local window = require "window"

-- Load users webview class
-- ("$XDG_CONFIG_HOME/luakit/webview.lua" or "/etc/xdg/luakit/webview.lua")
local webview = require "webview"

-- Add luakit;//log/ chrome page
local log_chrome = require "log_chrome"

window.add_signal("build", function (w)
    local widgets, l, r = require "lousy.widget", w.sbar.l, w.sbar.r

    -- Left-aligned status bar widgets
    l.layout:pack(widgets.uri())
    l.layout:pack(widgets.hist())
    l.layout:pack(widgets.progress())

    -- Right-aligned status bar widgets
    r.layout:pack(widgets.buf())
    r.layout:pack(log_chrome.widget())
    r.layout:pack(widgets.ssl())
    r.layout:pack(widgets.tabi())
    r.layout:pack(widgets.scroll())
end)

-- Load luakit binds and modes
local modes = require "modes"
local binds = require "binds"

local settings = require "settings"
require "settings_chrome"

----------------------------------
-- Optional user script loading --
----------------------------------


-- Put "userconf.lua" in your Luakit config dir with your own tweaks; if this is
-- permanent, no need to copy/paste/modify the default rc.lua whenever you
-- update Luakit.
if pcall(function () lousy.util.find_config("userconf.lua") end) then
    require "userconf"
end

-----------------------------
-- End user script loading --
-----------------------------

-- Restore last saved session

-- vim: et:sw=4:ts=8:sts=4:tw=80
```

Why do I get two tabs with this configuration? (and accessorily - can I slim it futher down?)

**Comment by taobert** [comment]
You don't mention what version you're using.
When i start a current `develop` build with the default `rc.lua` using `luakit -u http://example.com` i get only one tab.
When i do the same with your code as an `rc.lua`, it aborts with "[    0.083533] F [core/luakit]: no windows spawned by rc file, exiting".
It looks like you've deleted the code between "-- Restore last saved session" and "-- vim: et:sw=4:ts=8:sts=4:tw=80" which actually makes a window, and that what you tested with is not actually what you posted.

I'm not sure what you're trying to achieve with your minimal config. If you're hoping that this will speed things up/use less memory, then i think (possibly incorrectly) that you're mistaken, and that the bulk of the startup time/memory usage/cpu load comes from webkit-gtk rather than lua modules (this is addressed in slightly more detail in #905).
If it's just an exercise in code golf, then i have [a branch](https://github.com/taobert/luakit/tree/deprecate-lfs) without the `lfs` dependency, so you could remove that line.
I also suspect that any of the `local` requires which are not subsequently referenced are probably unnecessary. I haven't tested that extensively, but _did_ just comment out the `local webview = require "webview"` lines in both my `rc.lua` and `userconf.lua`, as well as the code which uses these local variables, and luakit seemed to load ok.

**Comment by wsw70** [comment]
First of all thank you for all your help!

> You don't mention what version you're using.

```
luakit 2.0.0
  built with webkit 2.22.6 (installed version: 2.32.3)
```

> When i start a current `develop` build with the default `rc.lua` using `luakit -u http://example.com` i get only one tab.
> When i do the same with your code as an `rc.lua`, it aborts

You are right. The reason for that is that I did not understand how the startup files work (you helped me to understand that in https://github.com/luakit/luakit/issues/952).

What I had was:
- a modified `/etc/xdg/luakit/rc.lua` like the one above
- a modified `.config/luakit/userconf.lua` like the one above, and with an extr line `window.new(uris)`

I therefore believe I was running the core configuration twice, and this will probably be the reason for the two tabs.

I will now switch to as single  `.config/luakit/rc.lua` (and remove  `.config/luakit/userconf.lua`) which will hopefully fix the two tabs (I will check that once at home, and close the issue)

> I'm not sure what you're trying to achieve with your minimal config.

I had some problems with `luakit` starting with a blank window until I clicked on it. It trued out to be a problem with the adblocker (removing it fixed the issue). In the same vein, I would like to cut on dependencies that I do not need to avoid possible problems down the road (`luakit` runs in kiosk mode, displaying my home dashboard so I control everything that is displayed)

**Comment by wsw70** [comment]
> I will now switch to as single `.config/luakit/rc.lua` (and remove `.config/luakit/userconf.lua`) which will hopefully fix the two tabs (I will check that once at home, and close the issue)

Yes, that was it - the single, sensible `rc.lua` works fine, thanks again!
