### ISSUE TITLE
[question] How to override the global settings?

### ISSUE THREAD

**Issue by wsw70** [luakit/luakit#952]
The documentation [lists the configuration files](https://luakit.github.io/docs/pages/03-quick-start-guide.html) that are parsed upon start. 

I created a file `~/.config/luakit/userconf.lua` expecting that it will be parsed **instead of** the global once in `/etc/xdg/luakit/`. It did not, the global one was still aprsed. 

I ended up editing the global one - which is a terrible approach as it will be replaced at the next update of `luakit`.

Is there a way to parse and stop further parsing?

**Comment by taobert** [comment]
When luakit starts it finds an `rc.lua` file and sources that. `rc.lua` in turn loads `userconf.lua`.
If you copy `/etc/xdg/luakit/rc.lua` into `~/.config/luakit/` then the local copy will be used instead of the system copy (unless there is a problem with the local copy which causes startup to abort, in which case starting up with the system file will be attempted).
There seems to be a policy that at some stage, user-level `rc.lua` will be deprecated, with only the `userconf.lua` being necessary, but that's a ways off.

**Comment by wsw70** [comment]
> When luakit starts it finds an `rc.lua` file and sources that. `rc.lua` in turn loads `userconf.lua`.

Ah yes - I was just working on  `userconf.lua`, which indeed does not makes sense as this file is sources from within rc.lua`. Thank you for the clarification.
