### ISSUE TITLE
[Question] How to change items in right-click context menu?

### ISSUE THREAD

**Issue by MuhammedZakir** [luakit/luakit#962]
Can I add or remove items in right-click context menu? Mainly, I want to execute some lua/js functions when those items are clicked.

**Comment by c0dev0id** [comment]
I haven't played with it, but I think this should be possible: https://luakit.github.io/docs/classes/widget:webview.html#signal-populate-popup

**Comment by MuhammedZakir** [comment]
Thanks! :-)

I can't get it working. Nothing happens when the context-menu is shown.

In `my_signals.lua`:
```lua
local webview = require 'webview'
local prettyPrint = require 'vendor/inspect'

webview.add_signal("populate-popup", function (menu)
  print("populate-popup")
  prettyPrint(menu)
  menu["test"] = function () prettyPrint("asd") end
end)
```

In `userconf.lua`:
```lua
-- at the top
require "my_signals"
```

I am also confused about "UI Lua State". Is there some explanation for that? 

Edit: corrected file name and import.

**Comment by taobert** [comment]
The entry for `populate-popup` is a bit light, and could be expanded if someone had the inclination to do so.
I got some extra hints from #482 and #738, and  `table_from_context_menu()` and `context_menu_from_table()` in `widgets/webview.c`.

I think that the first argument to a signal handler is the thing that the signal is raised on,
and that any parameters listed in the API start at the second argument.
I also think that you may need to wrap this all in an `init` signal handler.
Further, `menu` is a list of tables, rather than an associative array.
It also looks like adding a `true` to the list draws a horizontal line/menu separator.

For me, (using `penlight` which i have installed and am familiar with, rather than `vendor/inspect`) 
putting the following in my `userconf.lua` changes the menu as (i believe) you want:
```lua
local webview = require 'webview'
webview.add_signal("init", function (view)
    view:add_signal("populate-popup", function (_, menu)
	--local prettyPrint = require 'vendor/inspect'
	local prettyPrint = require('pl.pretty').dump
	table.insert(menu, {"New Reload", 13})
	table.insert(menu, true)
	table.insert(menu, {"Test", function () prettyPrint("asd") end})
	prettyPrint(menu)
    end)
end)
```
The inbuilt webkit items reference magic numbers in webkit space (linked to from #482) for their actions,
but the lua closure also fires fine.

I also notice that if there's something in the primary buffer,
a final entry gets added to the menu after this signal handler gets called,
offering to search for that string using one of the defined search engines.
I'm not sure where this gets added and i don't know what other things might get added in other situations,
so you shouldn't assume that the menu you're presented with/build is what you'll end up with.


Regarding "UI Lua State", i'm not quite sure what you're asking about, though i assume you're asking after having read the term in the IPC API. As i understand it, a lua state is another name for a virtual machine. This virtual machine is constrained to the process it's embedded in. Luakit uses a single process to do the UI, but webkit also has a number of WebKitWebProcesses, which do much of the heavy lifting (and chew up a lot of memory). The IPC module facilitates shifting information between the lua state of the UI process, and those of the WebProcesses. Luakit modules which run on the WebProcesses (i think, but perhaps they're on the UI process, and just communicate with web processes) tend to be suffixed "_wm" for web module.

**Comment by MuhammedZakir** [comment]
It's working. Thanks for detailed explanation! :-)
