### ISSUE TITLE
Key sequences not working in input mode.

### ISSUE THREAD

**Issue by Iron-Chancellor** [luakit/luakit#964]
**userconf.lua**
modes.add_binds("all",{
{"jf","Return to `normal` mode.",function(w) w:set_mode() end},
{"fj","Return to `normal` mode.",function(w) w:set_mode() end},
})

**Current Behavior:**
Pressing "jf" nor "fj" in input mode doesn't return to normal mode.

**Desired Behavior:**
Pressing the j and f keys at the same time exits input mode.

**How can we reproduce it (step by step):**
1. Paste the command above into userconf.lua
2. Run luakit
3. Press i
4. Press the j and f keys at the same time

**Environment:**

Linux Distribution & Version: Archlinux ARM current.
Output of `luakit --version`:
luakit 2.3
  built with webkit 2.30.6 (installed version: 2.32.4)

**Comment by taobert** [comment]
Your reproduction instructions stipulate that the keys are to be pressed "at the same time".
This is not currently feasible, as (i think) luakit has no infrastructure for binding things this way.
(I don't think there's currently a way to identify key-down/-up events, there's just key-press. Modifiers (Ctrl/Alt/Mod-4/Shift) are dealt with explicitly.) The binding you've created would (in normal mode) fire if 'j' were pressed and released, followed by 'f'.

Further confounding your efforts is the fact that keys are buffered, (so that multi-character bindings can be matched) _only_ if the window's in `normal` mode. You could override this behaviour by writing your own version of window.hit() (copying and amending from `lib/window.lua`):
```lua
local window = require "window"
-- Wrapper around the bind plugin's hit method
window.methods.hit = function (w, mods, key, opts)
    opts = lousy.util.table.join(opts or {}, {
	    enable_buffer = w:is_mode("normal") or w:is_mode("insert"),
	    buffer = w.buffer,
	    })

    local caught, newbuf = lousy.bind.hit(w, w.binds, mods, key, opts)
    if w.win then -- Check binding didn't cause window to exit
	w.buffer = newbuf
	w:update_buf()
    end
    return caught
end
```
With this your keybindings will exit insert mode when you press the final key of the sequence,
however the preceding keys still get put in the textarea/input.

There may be an elegant way to stop the preceding characters being displayed,
but in an emergency, you could rejig your keybinding to backspace out the extraneous character(s):
```lua
modes.add_binds("insert", {
    {"fj","Return to normal mode.",function(w) w.view:send_key("BackSpace"); w:set_mode() end},
    {"jf","Return to normal mode.",function(w) w.view:send_key("BackSpace"); w:set_mode() end},
})
```
However, that's so ugly that it makes me a little queasy. If you can cope with it, using the default `<Escape>` or some other single character binding (`<Control-c>`?) might leave you feeling better about yourself.

**Comment by Iron-Chancellor** [comment]
> There may be an elegant way to stop the preceding characters being displayed, but in an emergency, you could rejig your keybinding to backspace out the extraneous character(s):

This is actually exactly what I want it to do! I'm trying to replicate my VIM keybinds which will enter a 'j' or 'f' and then deletes it if the other key is pressed afterwards.

Thanks for the help!
