### ISSUE TITLE
building with different prefix causes errors:

### ISSUE THREAD

**Issue by FrostKnight** [luakit/luakit#969]
I tried building with make install PREFIX=/usr install  and this happens below: 

0.046557] W [core/luah]: loading rc '/home/localuser/.config/luakit/rc.lua' failed, falling back...
[    0.038288] I [core/luah]: Loading rc: /etc/xdg/luakit/rc.lua
[    0.038799] E [core/common/lualib]: Lua error: module 'unique_instance' not found:
                 	no field package.preload['unique_instance']
                 	no file './unique_instance.lua'
                 	no file '/usr/share/luajit-2.1.0-beta3/unique_instance.lua'
                 	no file '/usr/local/share/lua/5.1/unique_instance.lua'
                 	no file '/usr/local/share/lua/5.1/unique_instance/init.lua'
                 	no file '/usr/share/lua/5.1/unique_instance.lua'
                 	no file '/usr/share/lua/5.1/unique_instance/init.lua'
                 	no file '/usr/local/share/luakit/lib/unique_instance.lua'
                 	no file '/usr/local/share/luakit/lib/unique_instance/init.lua'
                 	no file '/home/localuser/.config/luakit/unique_instance.lua'
                 	no file '/home/localuser/.config/luakit/unique_instance/init.lua'
                 	no file '/etc/xdg/luakit/unique_instance.lua'
                 	no file '/etc/xdg/luakit/unique_instance/init.lua'
                 	no file './unique_instance.so'
                 	no file '/usr/local/lib/lua/5.1/unique_instance.so'
                 	no file '/usr/lib/lua/5.1/unique_instance.so'
                 	no file '/usr/local/lib/lua/5.1/loadall.so'
                 Traceback:
                 (1) [C]                       in function require
                 (2) /etc/xdg/luakit/rc.lua:25 in main chunk
[    0.038838] W [core/luah]: loading rc '/etc/xdg/luakit/rc.lua' failed, falling back...
[    0.034312] F [core/luakit]: couldn't find rc file

Not sure how to fix, I can get it working with the regular prefix, but it doesn't work with the other one. 
Any thoughts as to why this might happen? Either way, the browser looks like it might turn out to be good, just wondering how to fix.

**Comment by FrostKnight** [comment]
Everything else, I have, despite what the errors say. This distro uses a differenty way for the filesystems.

**Comment by MuhammedZakir** [comment]
Are you saying that lua libs are installed in `/usr/local/share/luakit/lib/`, but LuaKit is not able to load them?

---

I use a different prefix and is working fine for me. But, I changed them inside Makefile rather than passing them via cli for easy building.

```patch
diff --git a/Makefile b/Makefile
index 19a83cb..eb9597b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,11 @@
 # Include makefile config
 include config.mk
 
+# `make local`: configure local paths
+is-local := $(filter local, $(MAKECMDGOALS))
+PREFIX := $(if $(is-local), $(HOME)/.local, $(PREFIX))
+XDGPREFIX := $(if $(is-local), $(HOME)/.config, $(XDGPREFIX))
+
 # Token lib generation
 TLIST = common/tokenize.list
 THEAD = common/tokenize.h
@@ -17,6 +22,8 @@ EXT_OBJS = $(foreach obj,$(EXT_SRCS:.c=.o),$(obj))
 # Must be kept in sync with doc/docgen.ld
 DOC_SRCS = $(filter-out lib/markdown.lua lib/lousy/init.lua,$(shell for d in doc/luadoc lib common/clib; do find $$d -type f; done)) tests/lib.lua
 
+local: install
+
 all: options newline luakit luakit.1.gz luakit.so apidoc
 
 options:
@@ -134,4 +141,4 @@ run-tests: luakit luakit.so tests/util.so
 	@$(LUA_BIN_NAME) tests/run_test.lua
 
 newline: options;@echo
-.PHONY: all clean options install newline apidoc doc default
+.PHONY: all clean options install newline apidoc doc default buildopts.h local
```

**Comment by MuhammedZakir** [comment]
I am getting this error when I build after pulling the latest changes. The weird thing was that `luakit` is throwing that error when I built it from previous working commit (`26df055`) [1]. I may have updated my system after that LuaKit build, so maybe that's the cause? Any idea how to pinpoint the issue? I am using Manjaro btw.

[1] https://github.com/luakit/luakit/issues/968

**Comment by taobert** [comment]
`PREFIX` seems to work for me with current `develop`.
You don't specify, so forgive me if i'm off track, but per `README.md` you need to specify `PREFIX` for both `make` and `make install` (assuming you're compiling and installing as separate commands). `PREFIX` doesn't just tell make where to put stuff, it gets included in the executable (via `buildopts.h`, generated from `buildopts.h.in`), so that the executable knows where to load bits and pieces from.
If i omit `PREFIX` during compilation, and run `sudo make uninstall; make clean; make -j; sudo make PREFIX=/usr install`, then i get your "E [core/common/lualib]: Lua error: module 'unique_instance' not found:" error.

**Comment by taobert** [comment]
It _does_ seem, however, that `buildopts.h` is generated once, and then never updated, so that running `make; make PREFIX=/usr` won't behave as expected. So even if you _had_ used `PREFIX` as `README.md` suggests, failing to do a `make clean` beforehand may have prevented it working correctly. 

~~Also, `buildopts.h` is generated as a subordinate clause to `make doc`, which is at best counterintuitive, and probably leading to some of the unexpected behaviour.~~(Edit: this is wrong. `buildopts.h` is in `$(HEADS)`, and so required by object file creation.) Ideally `PREFIX` would be tested, and if it has changed since the last invocation, then `buildopts.h` should be regenerated.

**Comment by FrostKnight** [comment]
Yep, you were right, I didn't make clean and thats why even following your instructions failed a few times... 


make clean  && make -j4 PREFIX=/usr; doas make PREFIX=/usr install

That fixed my build, so yeah, you were correct, its an odd thing to have to do though I must admit, for now, I hope you preserve this bug's log as long as possible, if its never fixed, but yeah this can be closed I suppose.
