### ISSUE TITLE
[Question] HTTP/2 and HTTP/3 support.

### ISSUE THREAD

**Issue by grpineiro** [luakit/luakit#980]
From devtools, I noticed all requests are made using http/1.1. Does luakit support http/2 and 3? If yes, how do I configure it?

**Comment by taobert** [comment]
Luakit hands network transport off to webkitgtk.
According to [webkitgtk's 2.33.2 release announcement](https://webkitgtk.org/2021/06/08/webkitgtk2.33.2-released.html) HTTP/2 should now (since June last year) be available if webkitgtk is built with libsoup3.
It appears that Debian Sid is still shipping libsoup2.4, and so my guess is that that's what its webkitgtk is built against. You don't mention what system you're running, but my guess is that you'll have to do a fair bit of compiling yourself.
I haven't looked at webkitgtk's (or libsoup3's) docs beyond that release announcement, so i can't comment on whether HTTP/2 will need to be explicitly enabled programmatically. If it does, then _that_ would constitute a valid luakit feature request, and pull requests would be welcomed. (Edit: [This page](https://blog.tingping.se/2021/06/07/http2-in-libsoup.html) asserts that "The latest development release of libsoup 3, 2.99.8, now enables HTTP/2 by default", so it may be that no change need be made to luakit for HTTP/2.)

In the brief look i had at [libsoup's dev site](https://gitlab.gnome.org/GNOME/libsoup), i didn't see any mention of HTTP/3. This doesn't mean they're not working on it, but my guess is that you'll be waiting a while.

**Comment by grpineiro** [comment]
I think I figured out my problem, I use arch linux and installed luakit from the official repo, but webkit2gtk from the same repository depends on libsoup 2.74.2-2 and not libsoup3, as you detailed to work with http/2.

I still haven't gotten around to compiling webkit2gtk from the source code, but epiphany browser from the official repo uses a version of webkit2 built on top of libsoup3 and I can confirm that it already comes with http/2 enabled by default, so in theory i would just have to rebuild the webkit2gtk with libsoup3.

Should I close the issue?

**Comment by taobert** [comment]
At this stage, i think it can be closed. I gather that issues can be reopened later.
